/*
 * Veeam Backup & Replication REST API
 *
 * This document lists paths (endpoints) of the Veeam Backup & Replication REST API and operations that you can perform by sending HTTP requests to the paths.<br>Requests can contain parameters in their path, query and header. POST and PUT requests can include a request body with resource payload. In response, you receive a conventional HTTP response code, HTTP response header and an optional response body schema that contains a result model.<br>Parameters, request bodies, and response bodies are defined inline or refer to schemas defined globally. Some schemas are polymorphic.
 *
 * API version: 1.1-rev0
 * Contact: support@veeam.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)

// EComputerRecoveryTokenFiltersOrderColumn the model 'EComputerRecoveryTokenFiltersOrderColumn'
type EComputerRecoveryTokenFiltersOrderColumn string

// List of EComputerRecoveryTokenFiltersOrderColumn
const (
	ECOMPUTERRECOVERYTOKENFILTERSORDERCOLUMN_NAME EComputerRecoveryTokenFiltersOrderColumn = "Name"
	ECOMPUTERRECOVERYTOKENFILTERSORDERCOLUMN_EXPIRATION_DATE EComputerRecoveryTokenFiltersOrderColumn = "ExpirationDate"
)

func (v *EComputerRecoveryTokenFiltersOrderColumn) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := EComputerRecoveryTokenFiltersOrderColumn(value)
	for _, existing := range []EComputerRecoveryTokenFiltersOrderColumn{ "Name", "ExpirationDate",   } {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid EComputerRecoveryTokenFiltersOrderColumn", value)
}

// Ptr returns reference to EComputerRecoveryTokenFiltersOrderColumn value
func (v EComputerRecoveryTokenFiltersOrderColumn) Ptr() *EComputerRecoveryTokenFiltersOrderColumn {
	return &v
}

type NullableEComputerRecoveryTokenFiltersOrderColumn struct {
	value *EComputerRecoveryTokenFiltersOrderColumn
	isSet bool
}

func (v NullableEComputerRecoveryTokenFiltersOrderColumn) Get() *EComputerRecoveryTokenFiltersOrderColumn {
	return v.value
}

func (v *NullableEComputerRecoveryTokenFiltersOrderColumn) Set(val *EComputerRecoveryTokenFiltersOrderColumn) {
	v.value = val
	v.isSet = true
}

func (v NullableEComputerRecoveryTokenFiltersOrderColumn) IsSet() bool {
	return v.isSet
}

func (v *NullableEComputerRecoveryTokenFiltersOrderColumn) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEComputerRecoveryTokenFiltersOrderColumn(val *EComputerRecoveryTokenFiltersOrderColumn) *NullableEComputerRecoveryTokenFiltersOrderColumn {
	return &NullableEComputerRecoveryTokenFiltersOrderColumn{value: val, isSet: true}
}

func (v NullableEComputerRecoveryTokenFiltersOrderColumn) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEComputerRecoveryTokenFiltersOrderColumn) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

