/*
 * Veeam Backup & Replication REST API
 *
 * This document lists paths (endpoints) of the Veeam Backup & Replication REST API and operations that you can perform by sending HTTP requests to the paths.<br>Requests can contain parameters in their path, query and header. POST and PUT requests can include a request body with resource payload. In response, you receive a conventional HTTP response code, HTTP response header and an optional response body schema that contains a result model.<br>Parameters, request bodies, and response bodies are defined inline or refer to schemas defined globally. Some schemas are polymorphic.
 *
 * API version: 1.1-rev0
 * Contact: support@veeam.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// S3CompatibleRegionBrowserModel struct for S3CompatibleRegionBrowserModel
type S3CompatibleRegionBrowserModel struct {
	Id *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	Buckets *[]S3CompatibleBucketBrowserModel `json:"buckets,omitempty"`
}

// NewS3CompatibleRegionBrowserModel instantiates a new S3CompatibleRegionBrowserModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewS3CompatibleRegionBrowserModel() *S3CompatibleRegionBrowserModel {
	this := S3CompatibleRegionBrowserModel{}
	return &this
}

// NewS3CompatibleRegionBrowserModelWithDefaults instantiates a new S3CompatibleRegionBrowserModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewS3CompatibleRegionBrowserModelWithDefaults() *S3CompatibleRegionBrowserModel {
	this := S3CompatibleRegionBrowserModel{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *S3CompatibleRegionBrowserModel) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *S3CompatibleRegionBrowserModel) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *S3CompatibleRegionBrowserModel) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *S3CompatibleRegionBrowserModel) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *S3CompatibleRegionBrowserModel) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *S3CompatibleRegionBrowserModel) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *S3CompatibleRegionBrowserModel) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *S3CompatibleRegionBrowserModel) SetName(v string) {
	o.Name = &v
}

// GetBuckets returns the Buckets field value if set, zero value otherwise.
func (o *S3CompatibleRegionBrowserModel) GetBuckets() []S3CompatibleBucketBrowserModel {
	if o == nil || o.Buckets == nil {
		var ret []S3CompatibleBucketBrowserModel
		return ret
	}
	return *o.Buckets
}

// GetBucketsOk returns a tuple with the Buckets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *S3CompatibleRegionBrowserModel) GetBucketsOk() (*[]S3CompatibleBucketBrowserModel, bool) {
	if o == nil || o.Buckets == nil {
		return nil, false
	}
	return o.Buckets, true
}

// HasBuckets returns a boolean if a field has been set.
func (o *S3CompatibleRegionBrowserModel) HasBuckets() bool {
	if o != nil && o.Buckets != nil {
		return true
	}

	return false
}

// SetBuckets gets a reference to the given []S3CompatibleBucketBrowserModel and assigns it to the Buckets field.
func (o *S3CompatibleRegionBrowserModel) SetBuckets(v []S3CompatibleBucketBrowserModel) {
	o.Buckets = &v
}

func (o S3CompatibleRegionBrowserModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Buckets != nil {
		toSerialize["buckets"] = o.Buckets
	}
	return json.Marshal(toSerialize)
}

type NullableS3CompatibleRegionBrowserModel struct {
	value *S3CompatibleRegionBrowserModel
	isSet bool
}

func (v NullableS3CompatibleRegionBrowserModel) Get() *S3CompatibleRegionBrowserModel {
	return v.value
}

func (v *NullableS3CompatibleRegionBrowserModel) Set(val *S3CompatibleRegionBrowserModel) {
	v.value = val
	v.isSet = true
}

func (v NullableS3CompatibleRegionBrowserModel) IsSet() bool {
	return v.isSet
}

func (v *NullableS3CompatibleRegionBrowserModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableS3CompatibleRegionBrowserModel(val *S3CompatibleRegionBrowserModel) *NullableS3CompatibleRegionBrowserModel {
	return &NullableS3CompatibleRegionBrowserModel{value: val, isSet: true}
}

func (v NullableS3CompatibleRegionBrowserModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableS3CompatibleRegionBrowserModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


