/*
 * Veeam Backup & Replication REST API
 *
 * This document lists paths (endpoints) of the Veeam Backup & Replication REST API and operations that you can perform by sending HTTP requests to the paths.<br>Requests can contain parameters in their path, query and header. POST and PUT requests can include a request body with resource payload. In response, you receive a conventional HTTP response code, HTTP response header and an optional response body schema that contains a result model.<br>Parameters, request bodies, and response bodies are defined inline or refer to schemas defined globally. Some schemas are polymorphic.
 *
 * API version: 1.1-rev0
 * Contact: support@veeam.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// AmazonCloudCredentialsSpec struct for AmazonCloudCredentialsSpec
type AmazonCloudCredentialsSpec struct {
	CloudCredentialsSpec
	// ID of the access key.
	AccessKey string `json:"accessKey"`
	// Secret access key.
	SecretKey string `json:"secretKey"`
	// Tag used to identify the credentials record.
	Tag *string `json:"tag,omitempty"`
}

// NewAmazonCloudCredentialsSpec instantiates a new AmazonCloudCredentialsSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAmazonCloudCredentialsSpec(accessKey string, secretKey string, ) *AmazonCloudCredentialsSpec {
	this := AmazonCloudCredentialsSpec{}
	this.AccessKey = accessKey
	this.SecretKey = secretKey
	return &this
}

// NewAmazonCloudCredentialsSpecWithDefaults instantiates a new AmazonCloudCredentialsSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAmazonCloudCredentialsSpecWithDefaults() *AmazonCloudCredentialsSpec {
	this := AmazonCloudCredentialsSpec{}
	return &this
}

// GetAccessKey returns the AccessKey field value
func (o *AmazonCloudCredentialsSpec) GetAccessKey() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.AccessKey
}

// GetAccessKeyOk returns a tuple with the AccessKey field value
// and a boolean to check if the value has been set.
func (o *AmazonCloudCredentialsSpec) GetAccessKeyOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.AccessKey, true
}

// SetAccessKey sets field value
func (o *AmazonCloudCredentialsSpec) SetAccessKey(v string) {
	o.AccessKey = v
}

// GetSecretKey returns the SecretKey field value
func (o *AmazonCloudCredentialsSpec) GetSecretKey() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.SecretKey
}

// GetSecretKeyOk returns a tuple with the SecretKey field value
// and a boolean to check if the value has been set.
func (o *AmazonCloudCredentialsSpec) GetSecretKeyOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.SecretKey, true
}

// SetSecretKey sets field value
func (o *AmazonCloudCredentialsSpec) SetSecretKey(v string) {
	o.SecretKey = v
}

// GetTag returns the Tag field value if set, zero value otherwise.
func (o *AmazonCloudCredentialsSpec) GetTag() string {
	if o == nil || o.Tag == nil {
		var ret string
		return ret
	}
	return *o.Tag
}

// GetTagOk returns a tuple with the Tag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AmazonCloudCredentialsSpec) GetTagOk() (*string, bool) {
	if o == nil || o.Tag == nil {
		return nil, false
	}
	return o.Tag, true
}

// HasTag returns a boolean if a field has been set.
func (o *AmazonCloudCredentialsSpec) HasTag() bool {
	if o != nil && o.Tag != nil {
		return true
	}

	return false
}

// SetTag gets a reference to the given string and assigns it to the Tag field.
func (o *AmazonCloudCredentialsSpec) SetTag(v string) {
	o.Tag = &v
}

func (o AmazonCloudCredentialsSpec) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedCloudCredentialsSpec, errCloudCredentialsSpec := json.Marshal(o.CloudCredentialsSpec)
	if errCloudCredentialsSpec != nil {
		return []byte{}, errCloudCredentialsSpec
	}
	errCloudCredentialsSpec = json.Unmarshal([]byte(serializedCloudCredentialsSpec), &toSerialize)
	if errCloudCredentialsSpec != nil {
		return []byte{}, errCloudCredentialsSpec
	}
	if true {
		toSerialize["accessKey"] = o.AccessKey
	}
	if true {
		toSerialize["secretKey"] = o.SecretKey
	}
	if o.Tag != nil {
		toSerialize["tag"] = o.Tag
	}
	return json.Marshal(toSerialize)
}

type NullableAmazonCloudCredentialsSpec struct {
	value *AmazonCloudCredentialsSpec
	isSet bool
}

func (v NullableAmazonCloudCredentialsSpec) Get() *AmazonCloudCredentialsSpec {
	return v.value
}

func (v *NullableAmazonCloudCredentialsSpec) Set(val *AmazonCloudCredentialsSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableAmazonCloudCredentialsSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableAmazonCloudCredentialsSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAmazonCloudCredentialsSpec(val *AmazonCloudCredentialsSpec) *NullableAmazonCloudCredentialsSpec {
	return &NullableAmazonCloudCredentialsSpec{value: val, isSet: true}
}

func (v NullableAmazonCloudCredentialsSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAmazonCloudCredentialsSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


