/*
 * Veeam Backup & Replication REST API
 *
 * This document lists paths (endpoints) of the Veeam Backup & Replication REST API and operations that you can perform by sending HTTP requests to the paths.<br>Requests can contain parameters in their path, query and header. POST and PUT requests can include a request body with resource payload. In response, you receive a conventional HTTP response code, HTTP response header and an optional response body schema that contains a result model.<br>Parameters, request bodies, and response bodies are defined inline or refer to schemas defined globally. Some schemas are polymorphic.
 *
 * API version: 1.1-rev0
 * Contact: support@veeam.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// AzureBlobBrowserModel struct for AzureBlobBrowserModel
type AzureBlobBrowserModel struct {
	CloudBrowserModel
	HostId *string `json:"hostId,omitempty"`
	RegionType *EAzureRegionType `json:"regionType,omitempty"`
	Containers *[]AzureBlobContainerBrowserModel `json:"containers,omitempty"`
}

// NewAzureBlobBrowserModel instantiates a new AzureBlobBrowserModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAzureBlobBrowserModel() *AzureBlobBrowserModel {
	this := AzureBlobBrowserModel{}
	return &this
}

// NewAzureBlobBrowserModelWithDefaults instantiates a new AzureBlobBrowserModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAzureBlobBrowserModelWithDefaults() *AzureBlobBrowserModel {
	this := AzureBlobBrowserModel{}
	return &this
}

// GetHostId returns the HostId field value if set, zero value otherwise.
func (o *AzureBlobBrowserModel) GetHostId() string {
	if o == nil || o.HostId == nil {
		var ret string
		return ret
	}
	return *o.HostId
}

// GetHostIdOk returns a tuple with the HostId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AzureBlobBrowserModel) GetHostIdOk() (*string, bool) {
	if o == nil || o.HostId == nil {
		return nil, false
	}
	return o.HostId, true
}

// HasHostId returns a boolean if a field has been set.
func (o *AzureBlobBrowserModel) HasHostId() bool {
	if o != nil && o.HostId != nil {
		return true
	}

	return false
}

// SetHostId gets a reference to the given string and assigns it to the HostId field.
func (o *AzureBlobBrowserModel) SetHostId(v string) {
	o.HostId = &v
}

// GetRegionType returns the RegionType field value if set, zero value otherwise.
func (o *AzureBlobBrowserModel) GetRegionType() EAzureRegionType {
	if o == nil || o.RegionType == nil {
		var ret EAzureRegionType
		return ret
	}
	return *o.RegionType
}

// GetRegionTypeOk returns a tuple with the RegionType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AzureBlobBrowserModel) GetRegionTypeOk() (*EAzureRegionType, bool) {
	if o == nil || o.RegionType == nil {
		return nil, false
	}
	return o.RegionType, true
}

// HasRegionType returns a boolean if a field has been set.
func (o *AzureBlobBrowserModel) HasRegionType() bool {
	if o != nil && o.RegionType != nil {
		return true
	}

	return false
}

// SetRegionType gets a reference to the given EAzureRegionType and assigns it to the RegionType field.
func (o *AzureBlobBrowserModel) SetRegionType(v EAzureRegionType) {
	o.RegionType = &v
}

// GetContainers returns the Containers field value if set, zero value otherwise.
func (o *AzureBlobBrowserModel) GetContainers() []AzureBlobContainerBrowserModel {
	if o == nil || o.Containers == nil {
		var ret []AzureBlobContainerBrowserModel
		return ret
	}
	return *o.Containers
}

// GetContainersOk returns a tuple with the Containers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AzureBlobBrowserModel) GetContainersOk() (*[]AzureBlobContainerBrowserModel, bool) {
	if o == nil || o.Containers == nil {
		return nil, false
	}
	return o.Containers, true
}

// HasContainers returns a boolean if a field has been set.
func (o *AzureBlobBrowserModel) HasContainers() bool {
	if o != nil && o.Containers != nil {
		return true
	}

	return false
}

// SetContainers gets a reference to the given []AzureBlobContainerBrowserModel and assigns it to the Containers field.
func (o *AzureBlobBrowserModel) SetContainers(v []AzureBlobContainerBrowserModel) {
	o.Containers = &v
}

func (o AzureBlobBrowserModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedCloudBrowserModel, errCloudBrowserModel := json.Marshal(o.CloudBrowserModel)
	if errCloudBrowserModel != nil {
		return []byte{}, errCloudBrowserModel
	}
	errCloudBrowserModel = json.Unmarshal([]byte(serializedCloudBrowserModel), &toSerialize)
	if errCloudBrowserModel != nil {
		return []byte{}, errCloudBrowserModel
	}
	if o.HostId != nil {
		toSerialize["hostId"] = o.HostId
	}
	if o.RegionType != nil {
		toSerialize["regionType"] = o.RegionType
	}
	if o.Containers != nil {
		toSerialize["containers"] = o.Containers
	}
	return json.Marshal(toSerialize)
}

type NullableAzureBlobBrowserModel struct {
	value *AzureBlobBrowserModel
	isSet bool
}

func (v NullableAzureBlobBrowserModel) Get() *AzureBlobBrowserModel {
	return v.value
}

func (v *NullableAzureBlobBrowserModel) Set(val *AzureBlobBrowserModel) {
	v.value = val
	v.isSet = true
}

func (v NullableAzureBlobBrowserModel) IsSet() bool {
	return v.isSet
}

func (v *NullableAzureBlobBrowserModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAzureBlobBrowserModel(val *AzureBlobBrowserModel) *NullableAzureBlobBrowserModel {
	return &NullableAzureBlobBrowserModel{value: val, isSet: true}
}

func (v NullableAzureBlobBrowserModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAzureBlobBrowserModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


