/*
 * Veeam Backup & Replication REST API
 *
 * This document lists paths (endpoints) of the Veeam Backup & Replication REST API and operations that you can perform by sending HTTP requests to the paths.<br>Requests can contain parameters in their path, query and header. POST and PUT requests can include a request body with resource payload. In response, you receive a conventional HTTP response code, HTTP response header and an optional response body schema that contains a result model.<br>Parameters, request bodies, and response bodies are defined inline or refer to schemas defined globally. Some schemas are polymorphic.
 *
 * API version: 1.1-rev0
 * Contact: support@veeam.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// AzureDataBoxContainerBrowserModel struct for AzureDataBoxContainerBrowserModel
type AzureDataBoxContainerBrowserModel struct {
	Name *string `json:"name,omitempty"`
	Folders *[]string `json:"folders,omitempty"`
}

// NewAzureDataBoxContainerBrowserModel instantiates a new AzureDataBoxContainerBrowserModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAzureDataBoxContainerBrowserModel() *AzureDataBoxContainerBrowserModel {
	this := AzureDataBoxContainerBrowserModel{}
	return &this
}

// NewAzureDataBoxContainerBrowserModelWithDefaults instantiates a new AzureDataBoxContainerBrowserModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAzureDataBoxContainerBrowserModelWithDefaults() *AzureDataBoxContainerBrowserModel {
	this := AzureDataBoxContainerBrowserModel{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *AzureDataBoxContainerBrowserModel) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AzureDataBoxContainerBrowserModel) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *AzureDataBoxContainerBrowserModel) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *AzureDataBoxContainerBrowserModel) SetName(v string) {
	o.Name = &v
}

// GetFolders returns the Folders field value if set, zero value otherwise.
func (o *AzureDataBoxContainerBrowserModel) GetFolders() []string {
	if o == nil || o.Folders == nil {
		var ret []string
		return ret
	}
	return *o.Folders
}

// GetFoldersOk returns a tuple with the Folders field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AzureDataBoxContainerBrowserModel) GetFoldersOk() (*[]string, bool) {
	if o == nil || o.Folders == nil {
		return nil, false
	}
	return o.Folders, true
}

// HasFolders returns a boolean if a field has been set.
func (o *AzureDataBoxContainerBrowserModel) HasFolders() bool {
	if o != nil && o.Folders != nil {
		return true
	}

	return false
}

// SetFolders gets a reference to the given []string and assigns it to the Folders field.
func (o *AzureDataBoxContainerBrowserModel) SetFolders(v []string) {
	o.Folders = &v
}

func (o AzureDataBoxContainerBrowserModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Folders != nil {
		toSerialize["folders"] = o.Folders
	}
	return json.Marshal(toSerialize)
}

type NullableAzureDataBoxContainerBrowserModel struct {
	value *AzureDataBoxContainerBrowserModel
	isSet bool
}

func (v NullableAzureDataBoxContainerBrowserModel) Get() *AzureDataBoxContainerBrowserModel {
	return v.value
}

func (v *NullableAzureDataBoxContainerBrowserModel) Set(val *AzureDataBoxContainerBrowserModel) {
	v.value = val
	v.isSet = true
}

func (v NullableAzureDataBoxContainerBrowserModel) IsSet() bool {
	return v.isSet
}

func (v *NullableAzureDataBoxContainerBrowserModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAzureDataBoxContainerBrowserModel(val *AzureDataBoxContainerBrowserModel) *NullableAzureDataBoxContainerBrowserModel {
	return &NullableAzureDataBoxContainerBrowserModel{value: val, isSet: true}
}

func (v NullableAzureDataBoxContainerBrowserModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAzureDataBoxContainerBrowserModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


