/*
 * Veeam Backup & Replication REST API
 *
 * This document lists paths (endpoints) of the Veeam Backup & Replication REST API and operations that you can perform by sending HTTP requests to the paths.<br>Requests can contain parameters in their path, query and header. POST and PUT requests can include a request body with resource payload. In response, you receive a conventional HTTP response code, HTTP response header and an optional response body schema that contains a result model.<br>Parameters, request bodies, and response bodies are defined inline or refer to schemas defined globally. Some schemas are polymorphic.
 *
 * API version: 1.1-rev0
 * Contact: support@veeam.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// AzureComputeCloudCredentialsSubscriptionSpec struct for AzureComputeCloudCredentialsSubscriptionSpec
type AzureComputeCloudCredentialsSubscriptionSpec struct {
	TenantId string `json:"tenantId"`
	ApplicationId string `json:"applicationId"`
	// either secret or certificate + passphrase
	Secret *string `json:"secret,omitempty"`
	// in pfx format, either secret or certificate + password
	Certificate *string `json:"certificate,omitempty"`
	// either secret or certificate + password
	Password *string `json:"password,omitempty"`
}

// NewAzureComputeCloudCredentialsSubscriptionSpec instantiates a new AzureComputeCloudCredentialsSubscriptionSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAzureComputeCloudCredentialsSubscriptionSpec(tenantId string, applicationId string, ) *AzureComputeCloudCredentialsSubscriptionSpec {
	this := AzureComputeCloudCredentialsSubscriptionSpec{}
	this.TenantId = tenantId
	this.ApplicationId = applicationId
	return &this
}

// NewAzureComputeCloudCredentialsSubscriptionSpecWithDefaults instantiates a new AzureComputeCloudCredentialsSubscriptionSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAzureComputeCloudCredentialsSubscriptionSpecWithDefaults() *AzureComputeCloudCredentialsSubscriptionSpec {
	this := AzureComputeCloudCredentialsSubscriptionSpec{}
	return &this
}

// GetTenantId returns the TenantId field value
func (o *AzureComputeCloudCredentialsSubscriptionSpec) GetTenantId() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *AzureComputeCloudCredentialsSubscriptionSpec) GetTenantIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *AzureComputeCloudCredentialsSubscriptionSpec) SetTenantId(v string) {
	o.TenantId = v
}

// GetApplicationId returns the ApplicationId field value
func (o *AzureComputeCloudCredentialsSubscriptionSpec) GetApplicationId() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.ApplicationId
}

// GetApplicationIdOk returns a tuple with the ApplicationId field value
// and a boolean to check if the value has been set.
func (o *AzureComputeCloudCredentialsSubscriptionSpec) GetApplicationIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ApplicationId, true
}

// SetApplicationId sets field value
func (o *AzureComputeCloudCredentialsSubscriptionSpec) SetApplicationId(v string) {
	o.ApplicationId = v
}

// GetSecret returns the Secret field value if set, zero value otherwise.
func (o *AzureComputeCloudCredentialsSubscriptionSpec) GetSecret() string {
	if o == nil || o.Secret == nil {
		var ret string
		return ret
	}
	return *o.Secret
}

// GetSecretOk returns a tuple with the Secret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AzureComputeCloudCredentialsSubscriptionSpec) GetSecretOk() (*string, bool) {
	if o == nil || o.Secret == nil {
		return nil, false
	}
	return o.Secret, true
}

// HasSecret returns a boolean if a field has been set.
func (o *AzureComputeCloudCredentialsSubscriptionSpec) HasSecret() bool {
	if o != nil && o.Secret != nil {
		return true
	}

	return false
}

// SetSecret gets a reference to the given string and assigns it to the Secret field.
func (o *AzureComputeCloudCredentialsSubscriptionSpec) SetSecret(v string) {
	o.Secret = &v
}

// GetCertificate returns the Certificate field value if set, zero value otherwise.
func (o *AzureComputeCloudCredentialsSubscriptionSpec) GetCertificate() string {
	if o == nil || o.Certificate == nil {
		var ret string
		return ret
	}
	return *o.Certificate
}

// GetCertificateOk returns a tuple with the Certificate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AzureComputeCloudCredentialsSubscriptionSpec) GetCertificateOk() (*string, bool) {
	if o == nil || o.Certificate == nil {
		return nil, false
	}
	return o.Certificate, true
}

// HasCertificate returns a boolean if a field has been set.
func (o *AzureComputeCloudCredentialsSubscriptionSpec) HasCertificate() bool {
	if o != nil && o.Certificate != nil {
		return true
	}

	return false
}

// SetCertificate gets a reference to the given string and assigns it to the Certificate field.
func (o *AzureComputeCloudCredentialsSubscriptionSpec) SetCertificate(v string) {
	o.Certificate = &v
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *AzureComputeCloudCredentialsSubscriptionSpec) GetPassword() string {
	if o == nil || o.Password == nil {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AzureComputeCloudCredentialsSubscriptionSpec) GetPasswordOk() (*string, bool) {
	if o == nil || o.Password == nil {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *AzureComputeCloudCredentialsSubscriptionSpec) HasPassword() bool {
	if o != nil && o.Password != nil {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *AzureComputeCloudCredentialsSubscriptionSpec) SetPassword(v string) {
	o.Password = &v
}

func (o AzureComputeCloudCredentialsSubscriptionSpec) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["tenantId"] = o.TenantId
	}
	if true {
		toSerialize["applicationId"] = o.ApplicationId
	}
	if o.Secret != nil {
		toSerialize["secret"] = o.Secret
	}
	if o.Certificate != nil {
		toSerialize["certificate"] = o.Certificate
	}
	if o.Password != nil {
		toSerialize["password"] = o.Password
	}
	return json.Marshal(toSerialize)
}

type NullableAzureComputeCloudCredentialsSubscriptionSpec struct {
	value *AzureComputeCloudCredentialsSubscriptionSpec
	isSet bool
}

func (v NullableAzureComputeCloudCredentialsSubscriptionSpec) Get() *AzureComputeCloudCredentialsSubscriptionSpec {
	return v.value
}

func (v *NullableAzureComputeCloudCredentialsSubscriptionSpec) Set(val *AzureComputeCloudCredentialsSubscriptionSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableAzureComputeCloudCredentialsSubscriptionSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableAzureComputeCloudCredentialsSubscriptionSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAzureComputeCloudCredentialsSubscriptionSpec(val *AzureComputeCloudCredentialsSubscriptionSpec) *NullableAzureComputeCloudCredentialsSubscriptionSpec {
	return &NullableAzureComputeCloudCredentialsSubscriptionSpec{value: val, isSet: true}
}

func (v NullableAzureComputeCloudCredentialsSubscriptionSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAzureComputeCloudCredentialsSubscriptionSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


