/*
 * Veeam Backup & Replication REST API
 *
 * This document lists paths (endpoints) of the Veeam Backup & Replication REST API and operations that you can perform by sending HTTP requests to the paths.<br>Requests can contain parameters in their path, query and header. POST and PUT requests can include a request body with resource payload. In response, you receive a conventional HTTP response code, HTTP response header and an optional response body schema that contains a result model.<br>Parameters, request bodies, and response bodies are defined inline or refer to schemas defined globally. Some schemas are polymorphic.
 *
 * API version: 1.1-rev0
 * Contact: support@veeam.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// AzureComputeCloudCredentialsModelAllOf struct for AzureComputeCloudCredentialsModelAllOf
type AzureComputeCloudCredentialsModelAllOf struct {
	Deployment AzureComputeCloudCredentialsDeploymentModel `json:"deployment"`
	Subscription AzureComputeCloudCredentialsSubscriptionModel `json:"subscription"`
	// Tag used to identify the credentials record.
	Tag *string `json:"tag,omitempty"`
}

// NewAzureComputeCloudCredentialsModelAllOf instantiates a new AzureComputeCloudCredentialsModelAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAzureComputeCloudCredentialsModelAllOf(deployment AzureComputeCloudCredentialsDeploymentModel, subscription AzureComputeCloudCredentialsSubscriptionModel, ) *AzureComputeCloudCredentialsModelAllOf {
	this := AzureComputeCloudCredentialsModelAllOf{}
	this.Deployment = deployment
	this.Subscription = subscription
	return &this
}

// NewAzureComputeCloudCredentialsModelAllOfWithDefaults instantiates a new AzureComputeCloudCredentialsModelAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAzureComputeCloudCredentialsModelAllOfWithDefaults() *AzureComputeCloudCredentialsModelAllOf {
	this := AzureComputeCloudCredentialsModelAllOf{}
	return &this
}

// GetDeployment returns the Deployment field value
func (o *AzureComputeCloudCredentialsModelAllOf) GetDeployment() AzureComputeCloudCredentialsDeploymentModel {
	if o == nil  {
		var ret AzureComputeCloudCredentialsDeploymentModel
		return ret
	}

	return o.Deployment
}

// GetDeploymentOk returns a tuple with the Deployment field value
// and a boolean to check if the value has been set.
func (o *AzureComputeCloudCredentialsModelAllOf) GetDeploymentOk() (*AzureComputeCloudCredentialsDeploymentModel, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Deployment, true
}

// SetDeployment sets field value
func (o *AzureComputeCloudCredentialsModelAllOf) SetDeployment(v AzureComputeCloudCredentialsDeploymentModel) {
	o.Deployment = v
}

// GetSubscription returns the Subscription field value
func (o *AzureComputeCloudCredentialsModelAllOf) GetSubscription() AzureComputeCloudCredentialsSubscriptionModel {
	if o == nil  {
		var ret AzureComputeCloudCredentialsSubscriptionModel
		return ret
	}

	return o.Subscription
}

// GetSubscriptionOk returns a tuple with the Subscription field value
// and a boolean to check if the value has been set.
func (o *AzureComputeCloudCredentialsModelAllOf) GetSubscriptionOk() (*AzureComputeCloudCredentialsSubscriptionModel, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Subscription, true
}

// SetSubscription sets field value
func (o *AzureComputeCloudCredentialsModelAllOf) SetSubscription(v AzureComputeCloudCredentialsSubscriptionModel) {
	o.Subscription = v
}

// GetTag returns the Tag field value if set, zero value otherwise.
func (o *AzureComputeCloudCredentialsModelAllOf) GetTag() string {
	if o == nil || o.Tag == nil {
		var ret string
		return ret
	}
	return *o.Tag
}

// GetTagOk returns a tuple with the Tag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AzureComputeCloudCredentialsModelAllOf) GetTagOk() (*string, bool) {
	if o == nil || o.Tag == nil {
		return nil, false
	}
	return o.Tag, true
}

// HasTag returns a boolean if a field has been set.
func (o *AzureComputeCloudCredentialsModelAllOf) HasTag() bool {
	if o != nil && o.Tag != nil {
		return true
	}

	return false
}

// SetTag gets a reference to the given string and assigns it to the Tag field.
func (o *AzureComputeCloudCredentialsModelAllOf) SetTag(v string) {
	o.Tag = &v
}

func (o AzureComputeCloudCredentialsModelAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["deployment"] = o.Deployment
	}
	if true {
		toSerialize["subscription"] = o.Subscription
	}
	if o.Tag != nil {
		toSerialize["tag"] = o.Tag
	}
	return json.Marshal(toSerialize)
}

type NullableAzureComputeCloudCredentialsModelAllOf struct {
	value *AzureComputeCloudCredentialsModelAllOf
	isSet bool
}

func (v NullableAzureComputeCloudCredentialsModelAllOf) Get() *AzureComputeCloudCredentialsModelAllOf {
	return v.value
}

func (v *NullableAzureComputeCloudCredentialsModelAllOf) Set(val *AzureComputeCloudCredentialsModelAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableAzureComputeCloudCredentialsModelAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableAzureComputeCloudCredentialsModelAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAzureComputeCloudCredentialsModelAllOf(val *AzureComputeCloudCredentialsModelAllOf) *NullableAzureComputeCloudCredentialsModelAllOf {
	return &NullableAzureComputeCloudCredentialsModelAllOf{value: val, isSet: true}
}

func (v NullableAzureComputeCloudCredentialsModelAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAzureComputeCloudCredentialsModelAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


