/*
 * Veeam Backup & Replication REST API
 *
 * This document lists paths (endpoints) of the Veeam Backup & Replication REST API and operations that you can perform by sending HTTP requests to the paths.<br>Requests can contain parameters in their path, query and header. POST and PUT requests can include a request body with resource payload. In response, you receive a conventional HTTP response code, HTTP response header and an optional response body schema that contains a result model.<br>Parameters, request bodies, and response bodies are defined inline or refer to schemas defined globally. Some schemas are polymorphic.
 *
 * API version: 1.1-rev0
 * Contact: support@veeam.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)

// EAmazonRegionType Amazon region type.
type EAmazonRegionType string

// List of EAmazonRegionType
const (
	EAMAZONREGIONTYPE_CHINA EAmazonRegionType = "China"
	EAMAZONREGIONTYPE_GLOBAL EAmazonRegionType = "Global"
	EAMAZONREGIONTYPE_GOVERNMENT EAmazonRegionType = "Government"
)

func (v *EAmazonRegionType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := EAmazonRegionType(value)
	for _, existing := range []EAmazonRegionType{ "China", "Global", "Government",   } {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid EAmazonRegionType", value)
}

// Ptr returns reference to EAmazonRegionType value
func (v EAmazonRegionType) Ptr() *EAmazonRegionType {
	return &v
}

type NullableEAmazonRegionType struct {
	value *EAmazonRegionType
	isSet bool
}

func (v NullableEAmazonRegionType) Get() *EAmazonRegionType {
	return v.value
}

func (v *NullableEAmazonRegionType) Set(val *EAmazonRegionType) {
	v.value = val
	v.isSet = true
}

func (v NullableEAmazonRegionType) IsSet() bool {
	return v.isSet
}

func (v *NullableEAmazonRegionType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEAmazonRegionType(val *EAmazonRegionType) *NullableEAmazonRegionType {
	return &NullableEAmazonRegionType{value: val, isSet: true}
}

func (v NullableEAmazonRegionType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEAmazonRegionType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

