/*
 * Veeam Backup & Replication REST API
 *
 * This document lists paths (endpoints) of the Veeam Backup & Replication REST API and operations that you can perform by sending HTTP requests to the paths.<br>Requests can contain parameters in their path, query and header. POST and PUT requests can include a request body with resource payload. In response, you receive a conventional HTTP response code, HTTP response header and an optional response body schema that contains a result model.<br>Parameters, request bodies, and response bodies are defined inline or refer to schemas defined globally. Some schemas are polymorphic.
 *
 * API version: 1.1-rev0
 * Contact: support@veeam.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// AzureDataBoxBrowserSpec struct for AzureDataBoxBrowserSpec
type AzureDataBoxBrowserSpec struct {
	CloudBrowserSpec
	ServicePoint *string `json:"servicePoint,omitempty"`
	GatewayServerId *string `json:"gatewayServerId,omitempty"`
}

// NewAzureDataBoxBrowserSpec instantiates a new AzureDataBoxBrowserSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAzureDataBoxBrowserSpec() *AzureDataBoxBrowserSpec {
	this := AzureDataBoxBrowserSpec{}
	return &this
}

// NewAzureDataBoxBrowserSpecWithDefaults instantiates a new AzureDataBoxBrowserSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAzureDataBoxBrowserSpecWithDefaults() *AzureDataBoxBrowserSpec {
	this := AzureDataBoxBrowserSpec{}
	return &this
}

// GetServicePoint returns the ServicePoint field value if set, zero value otherwise.
func (o *AzureDataBoxBrowserSpec) GetServicePoint() string {
	if o == nil || o.ServicePoint == nil {
		var ret string
		return ret
	}
	return *o.ServicePoint
}

// GetServicePointOk returns a tuple with the ServicePoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AzureDataBoxBrowserSpec) GetServicePointOk() (*string, bool) {
	if o == nil || o.ServicePoint == nil {
		return nil, false
	}
	return o.ServicePoint, true
}

// HasServicePoint returns a boolean if a field has been set.
func (o *AzureDataBoxBrowserSpec) HasServicePoint() bool {
	if o != nil && o.ServicePoint != nil {
		return true
	}

	return false
}

// SetServicePoint gets a reference to the given string and assigns it to the ServicePoint field.
func (o *AzureDataBoxBrowserSpec) SetServicePoint(v string) {
	o.ServicePoint = &v
}

// GetGatewayServerId returns the GatewayServerId field value if set, zero value otherwise.
func (o *AzureDataBoxBrowserSpec) GetGatewayServerId() string {
	if o == nil || o.GatewayServerId == nil {
		var ret string
		return ret
	}
	return *o.GatewayServerId
}

// GetGatewayServerIdOk returns a tuple with the GatewayServerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AzureDataBoxBrowserSpec) GetGatewayServerIdOk() (*string, bool) {
	if o == nil || o.GatewayServerId == nil {
		return nil, false
	}
	return o.GatewayServerId, true
}

// HasGatewayServerId returns a boolean if a field has been set.
func (o *AzureDataBoxBrowserSpec) HasGatewayServerId() bool {
	if o != nil && o.GatewayServerId != nil {
		return true
	}

	return false
}

// SetGatewayServerId gets a reference to the given string and assigns it to the GatewayServerId field.
func (o *AzureDataBoxBrowserSpec) SetGatewayServerId(v string) {
	o.GatewayServerId = &v
}

func (o AzureDataBoxBrowserSpec) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedCloudBrowserSpec, errCloudBrowserSpec := json.Marshal(o.CloudBrowserSpec)
	if errCloudBrowserSpec != nil {
		return []byte{}, errCloudBrowserSpec
	}
	errCloudBrowserSpec = json.Unmarshal([]byte(serializedCloudBrowserSpec), &toSerialize)
	if errCloudBrowserSpec != nil {
		return []byte{}, errCloudBrowserSpec
	}
	if o.ServicePoint != nil {
		toSerialize["servicePoint"] = o.ServicePoint
	}
	if o.GatewayServerId != nil {
		toSerialize["gatewayServerId"] = o.GatewayServerId
	}
	return json.Marshal(toSerialize)
}

type NullableAzureDataBoxBrowserSpec struct {
	value *AzureDataBoxBrowserSpec
	isSet bool
}

func (v NullableAzureDataBoxBrowserSpec) Get() *AzureDataBoxBrowserSpec {
	return v.value
}

func (v *NullableAzureDataBoxBrowserSpec) Set(val *AzureDataBoxBrowserSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableAzureDataBoxBrowserSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableAzureDataBoxBrowserSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAzureDataBoxBrowserSpec(val *AzureDataBoxBrowserSpec) *NullableAzureDataBoxBrowserSpec {
	return &NullableAzureDataBoxBrowserSpec{value: val, isSet: true}
}

func (v NullableAzureDataBoxBrowserSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAzureDataBoxBrowserSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


