/*
 * Veeam Backup & Replication REST API
 *
 * This document lists paths (endpoints) of the Veeam Backup & Replication REST API and operations that you can perform by sending HTTP requests to the paths.<br>Requests can contain parameters in their path, query and header. POST and PUT requests can include a request body with resource payload. In response, you receive a conventional HTTP response code, HTTP response header and an optional response body schema that contains a result model.<br>Parameters, request bodies, and response bodies are defined inline or refer to schemas defined globally. Some schemas are polymorphic.
 *
 * API version: 1.1-rev0
 * Contact: support@veeam.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)

// ERepositoryConnectionType the model 'ERepositoryConnectionType'
type ERepositoryConnectionType string

// List of ERepositoryConnectionType
const (
	EREPOSITORYCONNECTIONTYPE_DIRECT ERepositoryConnectionType = "Direct"
	EREPOSITORYCONNECTIONTYPE_SELECTED_GATEWAY ERepositoryConnectionType = "SelectedGateway"
)

func (v *ERepositoryConnectionType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ERepositoryConnectionType(value)
	for _, existing := range []ERepositoryConnectionType{ "Direct", "SelectedGateway",   } {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ERepositoryConnectionType", value)
}

// Ptr returns reference to ERepositoryConnectionType value
func (v ERepositoryConnectionType) Ptr() *ERepositoryConnectionType {
	return &v
}

type NullableERepositoryConnectionType struct {
	value *ERepositoryConnectionType
	isSet bool
}

func (v NullableERepositoryConnectionType) Get() *ERepositoryConnectionType {
	return v.value
}

func (v *NullableERepositoryConnectionType) Set(val *ERepositoryConnectionType) {
	v.value = val
	v.isSet = true
}

func (v NullableERepositoryConnectionType) IsSet() bool {
	return v.isSet
}

func (v *NullableERepositoryConnectionType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableERepositoryConnectionType(val *ERepositoryConnectionType) *NullableERepositoryConnectionType {
	return &NullableERepositoryConnectionType{value: val, isSet: true}
}

func (v NullableERepositoryConnectionType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableERepositoryConnectionType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

