/*
 * Veeam Backup & Replication REST API
 *
 * This document lists paths (endpoints) of the Veeam Backup & Replication REST API and operations that you can perform by sending HTTP requests to the paths.<br>Requests can contain parameters in their path, query and header. POST and PUT requests can include a request body with resource payload. In response, you receive a conventional HTTP response code, HTTP response header and an optional response body schema that contains a result model.<br>Parameters, request bodies, and response bodies are defined inline or refer to schemas defined globally. Some schemas are polymorphic.
 *
 * API version: 1.1-rev0
 * Contact: support@veeam.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// AzureDataBoxStorageAccountImportModel struct for AzureDataBoxStorageAccountImportModel
type AzureDataBoxStorageAccountImportModel struct {
	ServiceEndpoint string `json:"serviceEndpoint"`
	Credentials CredentialsImportModel `json:"credentials"`
	GatewayServer RepositoryShareGatewayImportSpec `json:"gatewayServer"`
}

// NewAzureDataBoxStorageAccountImportModel instantiates a new AzureDataBoxStorageAccountImportModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAzureDataBoxStorageAccountImportModel(serviceEndpoint string, credentials CredentialsImportModel, gatewayServer RepositoryShareGatewayImportSpec, ) *AzureDataBoxStorageAccountImportModel {
	this := AzureDataBoxStorageAccountImportModel{}
	this.ServiceEndpoint = serviceEndpoint
	this.Credentials = credentials
	this.GatewayServer = gatewayServer
	return &this
}

// NewAzureDataBoxStorageAccountImportModelWithDefaults instantiates a new AzureDataBoxStorageAccountImportModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAzureDataBoxStorageAccountImportModelWithDefaults() *AzureDataBoxStorageAccountImportModel {
	this := AzureDataBoxStorageAccountImportModel{}
	return &this
}

// GetServiceEndpoint returns the ServiceEndpoint field value
func (o *AzureDataBoxStorageAccountImportModel) GetServiceEndpoint() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.ServiceEndpoint
}

// GetServiceEndpointOk returns a tuple with the ServiceEndpoint field value
// and a boolean to check if the value has been set.
func (o *AzureDataBoxStorageAccountImportModel) GetServiceEndpointOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ServiceEndpoint, true
}

// SetServiceEndpoint sets field value
func (o *AzureDataBoxStorageAccountImportModel) SetServiceEndpoint(v string) {
	o.ServiceEndpoint = v
}

// GetCredentials returns the Credentials field value
func (o *AzureDataBoxStorageAccountImportModel) GetCredentials() CredentialsImportModel {
	if o == nil  {
		var ret CredentialsImportModel
		return ret
	}

	return o.Credentials
}

// GetCredentialsOk returns a tuple with the Credentials field value
// and a boolean to check if the value has been set.
func (o *AzureDataBoxStorageAccountImportModel) GetCredentialsOk() (*CredentialsImportModel, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Credentials, true
}

// SetCredentials sets field value
func (o *AzureDataBoxStorageAccountImportModel) SetCredentials(v CredentialsImportModel) {
	o.Credentials = v
}

// GetGatewayServer returns the GatewayServer field value
func (o *AzureDataBoxStorageAccountImportModel) GetGatewayServer() RepositoryShareGatewayImportSpec {
	if o == nil  {
		var ret RepositoryShareGatewayImportSpec
		return ret
	}

	return o.GatewayServer
}

// GetGatewayServerOk returns a tuple with the GatewayServer field value
// and a boolean to check if the value has been set.
func (o *AzureDataBoxStorageAccountImportModel) GetGatewayServerOk() (*RepositoryShareGatewayImportSpec, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.GatewayServer, true
}

// SetGatewayServer sets field value
func (o *AzureDataBoxStorageAccountImportModel) SetGatewayServer(v RepositoryShareGatewayImportSpec) {
	o.GatewayServer = v
}

func (o AzureDataBoxStorageAccountImportModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["serviceEndpoint"] = o.ServiceEndpoint
	}
	if true {
		toSerialize["credentials"] = o.Credentials
	}
	if true {
		toSerialize["gatewayServer"] = o.GatewayServer
	}
	return json.Marshal(toSerialize)
}

type NullableAzureDataBoxStorageAccountImportModel struct {
	value *AzureDataBoxStorageAccountImportModel
	isSet bool
}

func (v NullableAzureDataBoxStorageAccountImportModel) Get() *AzureDataBoxStorageAccountImportModel {
	return v.value
}

func (v *NullableAzureDataBoxStorageAccountImportModel) Set(val *AzureDataBoxStorageAccountImportModel) {
	v.value = val
	v.isSet = true
}

func (v NullableAzureDataBoxStorageAccountImportModel) IsSet() bool {
	return v.isSet
}

func (v *NullableAzureDataBoxStorageAccountImportModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAzureDataBoxStorageAccountImportModel(val *AzureDataBoxStorageAccountImportModel) *NullableAzureDataBoxStorageAccountImportModel {
	return &NullableAzureDataBoxStorageAccountImportModel{value: val, isSet: true}
}

func (v NullableAzureDataBoxStorageAccountImportModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAzureDataBoxStorageAccountImportModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


