/*
 * Veeam Backup & Replication REST API
 *
 * This document lists paths (endpoints) of the Veeam Backup & Replication REST API and operations that you can perform by sending HTTP requests to the paths.<br>Requests can contain parameters in their path, query and header. POST and PUT requests can include a request body with resource payload. In response, you receive a conventional HTTP response code, HTTP response header and an optional response body schema that contains a result model.<br>Parameters, request bodies, and response bodies are defined inline or refer to schemas defined globally. Some schemas are polymorphic.
 *
 * API version: 1.1-rev0
 * Contact: support@veeam.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// AzureBlobStorageModelAllOf struct for AzureBlobStorageModelAllOf
type AzureBlobStorageModelAllOf struct {
	EnableTaskLimit *bool `json:"enableTaskLimit,omitempty"`
	// Maximum number of concurrent tasks.
	MaxTaskCount *int32 `json:"maxTaskCount,omitempty"`
	Account AzureBlobStorageAccountModel `json:"account"`
	Container AzureBlobStorageContainerModel `json:"container"`
	ProxyAppliance *AzureStorageProxyModel `json:"proxyAppliance,omitempty"`
	MountServer MountServerSettingsModel `json:"mountServer"`
}

// NewAzureBlobStorageModelAllOf instantiates a new AzureBlobStorageModelAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAzureBlobStorageModelAllOf(account AzureBlobStorageAccountModel, container AzureBlobStorageContainerModel, mountServer MountServerSettingsModel, ) *AzureBlobStorageModelAllOf {
	this := AzureBlobStorageModelAllOf{}
	this.Account = account
	this.Container = container
	this.MountServer = mountServer
	return &this
}

// NewAzureBlobStorageModelAllOfWithDefaults instantiates a new AzureBlobStorageModelAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAzureBlobStorageModelAllOfWithDefaults() *AzureBlobStorageModelAllOf {
	this := AzureBlobStorageModelAllOf{}
	return &this
}

// GetEnableTaskLimit returns the EnableTaskLimit field value if set, zero value otherwise.
func (o *AzureBlobStorageModelAllOf) GetEnableTaskLimit() bool {
	if o == nil || o.EnableTaskLimit == nil {
		var ret bool
		return ret
	}
	return *o.EnableTaskLimit
}

// GetEnableTaskLimitOk returns a tuple with the EnableTaskLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AzureBlobStorageModelAllOf) GetEnableTaskLimitOk() (*bool, bool) {
	if o == nil || o.EnableTaskLimit == nil {
		return nil, false
	}
	return o.EnableTaskLimit, true
}

// HasEnableTaskLimit returns a boolean if a field has been set.
func (o *AzureBlobStorageModelAllOf) HasEnableTaskLimit() bool {
	if o != nil && o.EnableTaskLimit != nil {
		return true
	}

	return false
}

// SetEnableTaskLimit gets a reference to the given bool and assigns it to the EnableTaskLimit field.
func (o *AzureBlobStorageModelAllOf) SetEnableTaskLimit(v bool) {
	o.EnableTaskLimit = &v
}

// GetMaxTaskCount returns the MaxTaskCount field value if set, zero value otherwise.
func (o *AzureBlobStorageModelAllOf) GetMaxTaskCount() int32 {
	if o == nil || o.MaxTaskCount == nil {
		var ret int32
		return ret
	}
	return *o.MaxTaskCount
}

// GetMaxTaskCountOk returns a tuple with the MaxTaskCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AzureBlobStorageModelAllOf) GetMaxTaskCountOk() (*int32, bool) {
	if o == nil || o.MaxTaskCount == nil {
		return nil, false
	}
	return o.MaxTaskCount, true
}

// HasMaxTaskCount returns a boolean if a field has been set.
func (o *AzureBlobStorageModelAllOf) HasMaxTaskCount() bool {
	if o != nil && o.MaxTaskCount != nil {
		return true
	}

	return false
}

// SetMaxTaskCount gets a reference to the given int32 and assigns it to the MaxTaskCount field.
func (o *AzureBlobStorageModelAllOf) SetMaxTaskCount(v int32) {
	o.MaxTaskCount = &v
}

// GetAccount returns the Account field value
func (o *AzureBlobStorageModelAllOf) GetAccount() AzureBlobStorageAccountModel {
	if o == nil  {
		var ret AzureBlobStorageAccountModel
		return ret
	}

	return o.Account
}

// GetAccountOk returns a tuple with the Account field value
// and a boolean to check if the value has been set.
func (o *AzureBlobStorageModelAllOf) GetAccountOk() (*AzureBlobStorageAccountModel, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Account, true
}

// SetAccount sets field value
func (o *AzureBlobStorageModelAllOf) SetAccount(v AzureBlobStorageAccountModel) {
	o.Account = v
}

// GetContainer returns the Container field value
func (o *AzureBlobStorageModelAllOf) GetContainer() AzureBlobStorageContainerModel {
	if o == nil  {
		var ret AzureBlobStorageContainerModel
		return ret
	}

	return o.Container
}

// GetContainerOk returns a tuple with the Container field value
// and a boolean to check if the value has been set.
func (o *AzureBlobStorageModelAllOf) GetContainerOk() (*AzureBlobStorageContainerModel, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Container, true
}

// SetContainer sets field value
func (o *AzureBlobStorageModelAllOf) SetContainer(v AzureBlobStorageContainerModel) {
	o.Container = v
}

// GetProxyAppliance returns the ProxyAppliance field value if set, zero value otherwise.
func (o *AzureBlobStorageModelAllOf) GetProxyAppliance() AzureStorageProxyModel {
	if o == nil || o.ProxyAppliance == nil {
		var ret AzureStorageProxyModel
		return ret
	}
	return *o.ProxyAppliance
}

// GetProxyApplianceOk returns a tuple with the ProxyAppliance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AzureBlobStorageModelAllOf) GetProxyApplianceOk() (*AzureStorageProxyModel, bool) {
	if o == nil || o.ProxyAppliance == nil {
		return nil, false
	}
	return o.ProxyAppliance, true
}

// HasProxyAppliance returns a boolean if a field has been set.
func (o *AzureBlobStorageModelAllOf) HasProxyAppliance() bool {
	if o != nil && o.ProxyAppliance != nil {
		return true
	}

	return false
}

// SetProxyAppliance gets a reference to the given AzureStorageProxyModel and assigns it to the ProxyAppliance field.
func (o *AzureBlobStorageModelAllOf) SetProxyAppliance(v AzureStorageProxyModel) {
	o.ProxyAppliance = &v
}

// GetMountServer returns the MountServer field value
func (o *AzureBlobStorageModelAllOf) GetMountServer() MountServerSettingsModel {
	if o == nil  {
		var ret MountServerSettingsModel
		return ret
	}

	return o.MountServer
}

// GetMountServerOk returns a tuple with the MountServer field value
// and a boolean to check if the value has been set.
func (o *AzureBlobStorageModelAllOf) GetMountServerOk() (*MountServerSettingsModel, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.MountServer, true
}

// SetMountServer sets field value
func (o *AzureBlobStorageModelAllOf) SetMountServer(v MountServerSettingsModel) {
	o.MountServer = v
}

func (o AzureBlobStorageModelAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.EnableTaskLimit != nil {
		toSerialize["enableTaskLimit"] = o.EnableTaskLimit
	}
	if o.MaxTaskCount != nil {
		toSerialize["maxTaskCount"] = o.MaxTaskCount
	}
	if true {
		toSerialize["account"] = o.Account
	}
	if true {
		toSerialize["container"] = o.Container
	}
	if o.ProxyAppliance != nil {
		toSerialize["proxyAppliance"] = o.ProxyAppliance
	}
	if true {
		toSerialize["mountServer"] = o.MountServer
	}
	return json.Marshal(toSerialize)
}

type NullableAzureBlobStorageModelAllOf struct {
	value *AzureBlobStorageModelAllOf
	isSet bool
}

func (v NullableAzureBlobStorageModelAllOf) Get() *AzureBlobStorageModelAllOf {
	return v.value
}

func (v *NullableAzureBlobStorageModelAllOf) Set(val *AzureBlobStorageModelAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableAzureBlobStorageModelAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableAzureBlobStorageModelAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAzureBlobStorageModelAllOf(val *AzureBlobStorageModelAllOf) *NullableAzureBlobStorageModelAllOf {
	return &NullableAzureBlobStorageModelAllOf{value: val, isSet: true}
}

func (v NullableAzureBlobStorageModelAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAzureBlobStorageModelAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


