/*
 * Veeam Backup & Replication REST API
 *
 * This document lists paths (endpoints) of the Veeam Backup & Replication REST API and operations that you can perform by sending HTTP requests to the paths.<br>Requests can contain parameters in their path, query and header. POST and PUT requests can include a request body with resource payload. In response, you receive a conventional HTTP response code, HTTP response header and an optional response body schema that contains a result model.<br>Parameters, request bodies, and response bodies are defined inline or refer to schemas defined globally. Some schemas are polymorphic.
 *
 * API version: 1.1-rev0
 * Contact: support@veeam.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// S3CompatibleBrowserModelAllOf struct for S3CompatibleBrowserModelAllOf
type S3CompatibleBrowserModelAllOf struct {
	HostId *string `json:"hostId,omitempty"`
	ConnectionPoint *string `json:"connectionPoint,omitempty"`
	Regions *[]S3CompatibleRegionBrowserModel `json:"regions,omitempty"`
}

// NewS3CompatibleBrowserModelAllOf instantiates a new S3CompatibleBrowserModelAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewS3CompatibleBrowserModelAllOf() *S3CompatibleBrowserModelAllOf {
	this := S3CompatibleBrowserModelAllOf{}
	return &this
}

// NewS3CompatibleBrowserModelAllOfWithDefaults instantiates a new S3CompatibleBrowserModelAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewS3CompatibleBrowserModelAllOfWithDefaults() *S3CompatibleBrowserModelAllOf {
	this := S3CompatibleBrowserModelAllOf{}
	return &this
}

// GetHostId returns the HostId field value if set, zero value otherwise.
func (o *S3CompatibleBrowserModelAllOf) GetHostId() string {
	if o == nil || o.HostId == nil {
		var ret string
		return ret
	}
	return *o.HostId
}

// GetHostIdOk returns a tuple with the HostId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *S3CompatibleBrowserModelAllOf) GetHostIdOk() (*string, bool) {
	if o == nil || o.HostId == nil {
		return nil, false
	}
	return o.HostId, true
}

// HasHostId returns a boolean if a field has been set.
func (o *S3CompatibleBrowserModelAllOf) HasHostId() bool {
	if o != nil && o.HostId != nil {
		return true
	}

	return false
}

// SetHostId gets a reference to the given string and assigns it to the HostId field.
func (o *S3CompatibleBrowserModelAllOf) SetHostId(v string) {
	o.HostId = &v
}

// GetConnectionPoint returns the ConnectionPoint field value if set, zero value otherwise.
func (o *S3CompatibleBrowserModelAllOf) GetConnectionPoint() string {
	if o == nil || o.ConnectionPoint == nil {
		var ret string
		return ret
	}
	return *o.ConnectionPoint
}

// GetConnectionPointOk returns a tuple with the ConnectionPoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *S3CompatibleBrowserModelAllOf) GetConnectionPointOk() (*string, bool) {
	if o == nil || o.ConnectionPoint == nil {
		return nil, false
	}
	return o.ConnectionPoint, true
}

// HasConnectionPoint returns a boolean if a field has been set.
func (o *S3CompatibleBrowserModelAllOf) HasConnectionPoint() bool {
	if o != nil && o.ConnectionPoint != nil {
		return true
	}

	return false
}

// SetConnectionPoint gets a reference to the given string and assigns it to the ConnectionPoint field.
func (o *S3CompatibleBrowserModelAllOf) SetConnectionPoint(v string) {
	o.ConnectionPoint = &v
}

// GetRegions returns the Regions field value if set, zero value otherwise.
func (o *S3CompatibleBrowserModelAllOf) GetRegions() []S3CompatibleRegionBrowserModel {
	if o == nil || o.Regions == nil {
		var ret []S3CompatibleRegionBrowserModel
		return ret
	}
	return *o.Regions
}

// GetRegionsOk returns a tuple with the Regions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *S3CompatibleBrowserModelAllOf) GetRegionsOk() (*[]S3CompatibleRegionBrowserModel, bool) {
	if o == nil || o.Regions == nil {
		return nil, false
	}
	return o.Regions, true
}

// HasRegions returns a boolean if a field has been set.
func (o *S3CompatibleBrowserModelAllOf) HasRegions() bool {
	if o != nil && o.Regions != nil {
		return true
	}

	return false
}

// SetRegions gets a reference to the given []S3CompatibleRegionBrowserModel and assigns it to the Regions field.
func (o *S3CompatibleBrowserModelAllOf) SetRegions(v []S3CompatibleRegionBrowserModel) {
	o.Regions = &v
}

func (o S3CompatibleBrowserModelAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.HostId != nil {
		toSerialize["hostId"] = o.HostId
	}
	if o.ConnectionPoint != nil {
		toSerialize["connectionPoint"] = o.ConnectionPoint
	}
	if o.Regions != nil {
		toSerialize["regions"] = o.Regions
	}
	return json.Marshal(toSerialize)
}

type NullableS3CompatibleBrowserModelAllOf struct {
	value *S3CompatibleBrowserModelAllOf
	isSet bool
}

func (v NullableS3CompatibleBrowserModelAllOf) Get() *S3CompatibleBrowserModelAllOf {
	return v.value
}

func (v *NullableS3CompatibleBrowserModelAllOf) Set(val *S3CompatibleBrowserModelAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableS3CompatibleBrowserModelAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableS3CompatibleBrowserModelAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableS3CompatibleBrowserModelAllOf(val *S3CompatibleBrowserModelAllOf) *NullableS3CompatibleBrowserModelAllOf {
	return &NullableS3CompatibleBrowserModelAllOf{value: val, isSet: true}
}

func (v NullableS3CompatibleBrowserModelAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableS3CompatibleBrowserModelAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


