/*
 * Veeam Backup & Replication REST API
 *
 * This document lists paths (endpoints) of the Veeam Backup & Replication REST API and operations that you can perform by sending HTTP requests to the paths.<br>Requests can contain parameters in their path, query and header. POST and PUT requests can include a request body with resource payload. In response, you receive a conventional HTTP response code, HTTP response header and an optional response body schema that contains a result model.<br>Parameters, request bodies, and response bodies are defined inline or refer to schemas defined globally. Some schemas are polymorphic.
 *
 * API version: 1.1-rev0
 * Contact: support@veeam.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// IBMCloudStorageModelAllOf struct for IBMCloudStorageModelAllOf
type IBMCloudStorageModelAllOf struct {
	EnableTaskLimit *bool `json:"enableTaskLimit,omitempty"`
	// Maximum number of concurrent tasks.
	MaxTaskCount *int32 `json:"maxTaskCount,omitempty"`
	Account IBMCloudStorageAccountModel `json:"account"`
	Bucket IBMCloudStorageBucketModel `json:"bucket"`
	MountServer MountServerSettingsModel `json:"mountServer"`
	ProxyAppliance *S3CompatibleProxyModel `json:"proxyAppliance,omitempty"`
}

// NewIBMCloudStorageModelAllOf instantiates a new IBMCloudStorageModelAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIBMCloudStorageModelAllOf(account IBMCloudStorageAccountModel, bucket IBMCloudStorageBucketModel, mountServer MountServerSettingsModel, ) *IBMCloudStorageModelAllOf {
	this := IBMCloudStorageModelAllOf{}
	this.Account = account
	this.Bucket = bucket
	this.MountServer = mountServer
	return &this
}

// NewIBMCloudStorageModelAllOfWithDefaults instantiates a new IBMCloudStorageModelAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIBMCloudStorageModelAllOfWithDefaults() *IBMCloudStorageModelAllOf {
	this := IBMCloudStorageModelAllOf{}
	return &this
}

// GetEnableTaskLimit returns the EnableTaskLimit field value if set, zero value otherwise.
func (o *IBMCloudStorageModelAllOf) GetEnableTaskLimit() bool {
	if o == nil || o.EnableTaskLimit == nil {
		var ret bool
		return ret
	}
	return *o.EnableTaskLimit
}

// GetEnableTaskLimitOk returns a tuple with the EnableTaskLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IBMCloudStorageModelAllOf) GetEnableTaskLimitOk() (*bool, bool) {
	if o == nil || o.EnableTaskLimit == nil {
		return nil, false
	}
	return o.EnableTaskLimit, true
}

// HasEnableTaskLimit returns a boolean if a field has been set.
func (o *IBMCloudStorageModelAllOf) HasEnableTaskLimit() bool {
	if o != nil && o.EnableTaskLimit != nil {
		return true
	}

	return false
}

// SetEnableTaskLimit gets a reference to the given bool and assigns it to the EnableTaskLimit field.
func (o *IBMCloudStorageModelAllOf) SetEnableTaskLimit(v bool) {
	o.EnableTaskLimit = &v
}

// GetMaxTaskCount returns the MaxTaskCount field value if set, zero value otherwise.
func (o *IBMCloudStorageModelAllOf) GetMaxTaskCount() int32 {
	if o == nil || o.MaxTaskCount == nil {
		var ret int32
		return ret
	}
	return *o.MaxTaskCount
}

// GetMaxTaskCountOk returns a tuple with the MaxTaskCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IBMCloudStorageModelAllOf) GetMaxTaskCountOk() (*int32, bool) {
	if o == nil || o.MaxTaskCount == nil {
		return nil, false
	}
	return o.MaxTaskCount, true
}

// HasMaxTaskCount returns a boolean if a field has been set.
func (o *IBMCloudStorageModelAllOf) HasMaxTaskCount() bool {
	if o != nil && o.MaxTaskCount != nil {
		return true
	}

	return false
}

// SetMaxTaskCount gets a reference to the given int32 and assigns it to the MaxTaskCount field.
func (o *IBMCloudStorageModelAllOf) SetMaxTaskCount(v int32) {
	o.MaxTaskCount = &v
}

// GetAccount returns the Account field value
func (o *IBMCloudStorageModelAllOf) GetAccount() IBMCloudStorageAccountModel {
	if o == nil  {
		var ret IBMCloudStorageAccountModel
		return ret
	}

	return o.Account
}

// GetAccountOk returns a tuple with the Account field value
// and a boolean to check if the value has been set.
func (o *IBMCloudStorageModelAllOf) GetAccountOk() (*IBMCloudStorageAccountModel, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Account, true
}

// SetAccount sets field value
func (o *IBMCloudStorageModelAllOf) SetAccount(v IBMCloudStorageAccountModel) {
	o.Account = v
}

// GetBucket returns the Bucket field value
func (o *IBMCloudStorageModelAllOf) GetBucket() IBMCloudStorageBucketModel {
	if o == nil  {
		var ret IBMCloudStorageBucketModel
		return ret
	}

	return o.Bucket
}

// GetBucketOk returns a tuple with the Bucket field value
// and a boolean to check if the value has been set.
func (o *IBMCloudStorageModelAllOf) GetBucketOk() (*IBMCloudStorageBucketModel, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Bucket, true
}

// SetBucket sets field value
func (o *IBMCloudStorageModelAllOf) SetBucket(v IBMCloudStorageBucketModel) {
	o.Bucket = v
}

// GetMountServer returns the MountServer field value
func (o *IBMCloudStorageModelAllOf) GetMountServer() MountServerSettingsModel {
	if o == nil  {
		var ret MountServerSettingsModel
		return ret
	}

	return o.MountServer
}

// GetMountServerOk returns a tuple with the MountServer field value
// and a boolean to check if the value has been set.
func (o *IBMCloudStorageModelAllOf) GetMountServerOk() (*MountServerSettingsModel, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.MountServer, true
}

// SetMountServer sets field value
func (o *IBMCloudStorageModelAllOf) SetMountServer(v MountServerSettingsModel) {
	o.MountServer = v
}

// GetProxyAppliance returns the ProxyAppliance field value if set, zero value otherwise.
func (o *IBMCloudStorageModelAllOf) GetProxyAppliance() S3CompatibleProxyModel {
	if o == nil || o.ProxyAppliance == nil {
		var ret S3CompatibleProxyModel
		return ret
	}
	return *o.ProxyAppliance
}

// GetProxyApplianceOk returns a tuple with the ProxyAppliance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IBMCloudStorageModelAllOf) GetProxyApplianceOk() (*S3CompatibleProxyModel, bool) {
	if o == nil || o.ProxyAppliance == nil {
		return nil, false
	}
	return o.ProxyAppliance, true
}

// HasProxyAppliance returns a boolean if a field has been set.
func (o *IBMCloudStorageModelAllOf) HasProxyAppliance() bool {
	if o != nil && o.ProxyAppliance != nil {
		return true
	}

	return false
}

// SetProxyAppliance gets a reference to the given S3CompatibleProxyModel and assigns it to the ProxyAppliance field.
func (o *IBMCloudStorageModelAllOf) SetProxyAppliance(v S3CompatibleProxyModel) {
	o.ProxyAppliance = &v
}

func (o IBMCloudStorageModelAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.EnableTaskLimit != nil {
		toSerialize["enableTaskLimit"] = o.EnableTaskLimit
	}
	if o.MaxTaskCount != nil {
		toSerialize["maxTaskCount"] = o.MaxTaskCount
	}
	if true {
		toSerialize["account"] = o.Account
	}
	if true {
		toSerialize["bucket"] = o.Bucket
	}
	if true {
		toSerialize["mountServer"] = o.MountServer
	}
	if o.ProxyAppliance != nil {
		toSerialize["proxyAppliance"] = o.ProxyAppliance
	}
	return json.Marshal(toSerialize)
}

type NullableIBMCloudStorageModelAllOf struct {
	value *IBMCloudStorageModelAllOf
	isSet bool
}

func (v NullableIBMCloudStorageModelAllOf) Get() *IBMCloudStorageModelAllOf {
	return v.value
}

func (v *NullableIBMCloudStorageModelAllOf) Set(val *IBMCloudStorageModelAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableIBMCloudStorageModelAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableIBMCloudStorageModelAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIBMCloudStorageModelAllOf(val *IBMCloudStorageModelAllOf) *NullableIBMCloudStorageModelAllOf {
	return &NullableIBMCloudStorageModelAllOf{value: val, isSet: true}
}

func (v NullableIBMCloudStorageModelAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIBMCloudStorageModelAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


