/*
 * Veeam Backup & Replication REST API
 *
 * This document lists paths (endpoints) of the Veeam Backup & Replication REST API and operations that you can perform by sending HTTP requests to the paths.<br>Requests can contain parameters in their path, query and header. POST and PUT requests can include a request body with resource payload. In response, you receive a conventional HTTP response code, HTTP response header and an optional response body schema that contains a result model.<br>Parameters, request bodies, and response bodies are defined inline or refer to schemas defined globally. Some schemas are polymorphic.
 *
 * API version: 1.1-rev0
 * Contact: support@veeam.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// GoogleCloudStorageBrowserDestinationSpec struct for GoogleCloudStorageBrowserDestinationSpec
type GoogleCloudStorageBrowserDestinationSpec struct {
	CloudBrowserNewFolderSpec
	HostId *string `json:"hostId,omitempty"`
	RegionId string `json:"regionId"`
	BucketName string `json:"bucketName"`
}

// NewGoogleCloudStorageBrowserDestinationSpec instantiates a new GoogleCloudStorageBrowserDestinationSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGoogleCloudStorageBrowserDestinationSpec(regionId string, bucketName string, ) *GoogleCloudStorageBrowserDestinationSpec {
	this := GoogleCloudStorageBrowserDestinationSpec{}
	this.RegionId = regionId
	this.BucketName = bucketName
	return &this
}

// NewGoogleCloudStorageBrowserDestinationSpecWithDefaults instantiates a new GoogleCloudStorageBrowserDestinationSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGoogleCloudStorageBrowserDestinationSpecWithDefaults() *GoogleCloudStorageBrowserDestinationSpec {
	this := GoogleCloudStorageBrowserDestinationSpec{}
	return &this
}

// GetHostId returns the HostId field value if set, zero value otherwise.
func (o *GoogleCloudStorageBrowserDestinationSpec) GetHostId() string {
	if o == nil || o.HostId == nil {
		var ret string
		return ret
	}
	return *o.HostId
}

// GetHostIdOk returns a tuple with the HostId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GoogleCloudStorageBrowserDestinationSpec) GetHostIdOk() (*string, bool) {
	if o == nil || o.HostId == nil {
		return nil, false
	}
	return o.HostId, true
}

// HasHostId returns a boolean if a field has been set.
func (o *GoogleCloudStorageBrowserDestinationSpec) HasHostId() bool {
	if o != nil && o.HostId != nil {
		return true
	}

	return false
}

// SetHostId gets a reference to the given string and assigns it to the HostId field.
func (o *GoogleCloudStorageBrowserDestinationSpec) SetHostId(v string) {
	o.HostId = &v
}

// GetRegionId returns the RegionId field value
func (o *GoogleCloudStorageBrowserDestinationSpec) GetRegionId() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.RegionId
}

// GetRegionIdOk returns a tuple with the RegionId field value
// and a boolean to check if the value has been set.
func (o *GoogleCloudStorageBrowserDestinationSpec) GetRegionIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.RegionId, true
}

// SetRegionId sets field value
func (o *GoogleCloudStorageBrowserDestinationSpec) SetRegionId(v string) {
	o.RegionId = v
}

// GetBucketName returns the BucketName field value
func (o *GoogleCloudStorageBrowserDestinationSpec) GetBucketName() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.BucketName
}

// GetBucketNameOk returns a tuple with the BucketName field value
// and a boolean to check if the value has been set.
func (o *GoogleCloudStorageBrowserDestinationSpec) GetBucketNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.BucketName, true
}

// SetBucketName sets field value
func (o *GoogleCloudStorageBrowserDestinationSpec) SetBucketName(v string) {
	o.BucketName = v
}

func (o GoogleCloudStorageBrowserDestinationSpec) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedCloudBrowserNewFolderSpec, errCloudBrowserNewFolderSpec := json.Marshal(o.CloudBrowserNewFolderSpec)
	if errCloudBrowserNewFolderSpec != nil {
		return []byte{}, errCloudBrowserNewFolderSpec
	}
	errCloudBrowserNewFolderSpec = json.Unmarshal([]byte(serializedCloudBrowserNewFolderSpec), &toSerialize)
	if errCloudBrowserNewFolderSpec != nil {
		return []byte{}, errCloudBrowserNewFolderSpec
	}
	if o.HostId != nil {
		toSerialize["hostId"] = o.HostId
	}
	if true {
		toSerialize["regionId"] = o.RegionId
	}
	if true {
		toSerialize["bucketName"] = o.BucketName
	}
	return json.Marshal(toSerialize)
}

type NullableGoogleCloudStorageBrowserDestinationSpec struct {
	value *GoogleCloudStorageBrowserDestinationSpec
	isSet bool
}

func (v NullableGoogleCloudStorageBrowserDestinationSpec) Get() *GoogleCloudStorageBrowserDestinationSpec {
	return v.value
}

func (v *NullableGoogleCloudStorageBrowserDestinationSpec) Set(val *GoogleCloudStorageBrowserDestinationSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableGoogleCloudStorageBrowserDestinationSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableGoogleCloudStorageBrowserDestinationSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGoogleCloudStorageBrowserDestinationSpec(val *GoogleCloudStorageBrowserDestinationSpec) *NullableGoogleCloudStorageBrowserDestinationSpec {
	return &NullableGoogleCloudStorageBrowserDestinationSpec{value: val, isSet: true}
}

func (v NullableGoogleCloudStorageBrowserDestinationSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGoogleCloudStorageBrowserDestinationSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


