/*
 * Veeam Backup & Replication REST API
 *
 * This document lists paths (endpoints) of the Veeam Backup & Replication REST API and operations that you can perform by sending HTTP requests to the paths.<br>Requests can contain parameters in their path, query and header. POST and PUT requests can include a request body with resource payload. In response, you receive a conventional HTTP response code, HTTP response header and an optional response body schema that contains a result model.<br>Parameters, request bodies, and response bodies are defined inline or refer to schemas defined globally. Some schemas are polymorphic.
 *
 * API version: 1.1-rev0
 * Contact: support@veeam.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// WasabiCloudStorageAccountModel Account used to access Wasabi storage.
type WasabiCloudStorageAccountModel struct {
	// ID of a region where the storage is located.
	RegionId string `json:"regionId"`
	// ID of a credentials record used to access the storage.
	CredentialsId string `json:"credentialsId"`
	ConnectionSettings *ObjectStorageConnectionModel `json:"connectionSettings,omitempty"`
}

// NewWasabiCloudStorageAccountModel instantiates a new WasabiCloudStorageAccountModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWasabiCloudStorageAccountModel(regionId string, credentialsId string, ) *WasabiCloudStorageAccountModel {
	this := WasabiCloudStorageAccountModel{}
	this.RegionId = regionId
	this.CredentialsId = credentialsId
	return &this
}

// NewWasabiCloudStorageAccountModelWithDefaults instantiates a new WasabiCloudStorageAccountModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWasabiCloudStorageAccountModelWithDefaults() *WasabiCloudStorageAccountModel {
	this := WasabiCloudStorageAccountModel{}
	return &this
}

// GetRegionId returns the RegionId field value
func (o *WasabiCloudStorageAccountModel) GetRegionId() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.RegionId
}

// GetRegionIdOk returns a tuple with the RegionId field value
// and a boolean to check if the value has been set.
func (o *WasabiCloudStorageAccountModel) GetRegionIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.RegionId, true
}

// SetRegionId sets field value
func (o *WasabiCloudStorageAccountModel) SetRegionId(v string) {
	o.RegionId = v
}

// GetCredentialsId returns the CredentialsId field value
func (o *WasabiCloudStorageAccountModel) GetCredentialsId() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.CredentialsId
}

// GetCredentialsIdOk returns a tuple with the CredentialsId field value
// and a boolean to check if the value has been set.
func (o *WasabiCloudStorageAccountModel) GetCredentialsIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.CredentialsId, true
}

// SetCredentialsId sets field value
func (o *WasabiCloudStorageAccountModel) SetCredentialsId(v string) {
	o.CredentialsId = v
}

// GetConnectionSettings returns the ConnectionSettings field value if set, zero value otherwise.
func (o *WasabiCloudStorageAccountModel) GetConnectionSettings() ObjectStorageConnectionModel {
	if o == nil || o.ConnectionSettings == nil {
		var ret ObjectStorageConnectionModel
		return ret
	}
	return *o.ConnectionSettings
}

// GetConnectionSettingsOk returns a tuple with the ConnectionSettings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WasabiCloudStorageAccountModel) GetConnectionSettingsOk() (*ObjectStorageConnectionModel, bool) {
	if o == nil || o.ConnectionSettings == nil {
		return nil, false
	}
	return o.ConnectionSettings, true
}

// HasConnectionSettings returns a boolean if a field has been set.
func (o *WasabiCloudStorageAccountModel) HasConnectionSettings() bool {
	if o != nil && o.ConnectionSettings != nil {
		return true
	}

	return false
}

// SetConnectionSettings gets a reference to the given ObjectStorageConnectionModel and assigns it to the ConnectionSettings field.
func (o *WasabiCloudStorageAccountModel) SetConnectionSettings(v ObjectStorageConnectionModel) {
	o.ConnectionSettings = &v
}

func (o WasabiCloudStorageAccountModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["regionId"] = o.RegionId
	}
	if true {
		toSerialize["credentialsId"] = o.CredentialsId
	}
	if o.ConnectionSettings != nil {
		toSerialize["connectionSettings"] = o.ConnectionSettings
	}
	return json.Marshal(toSerialize)
}

type NullableWasabiCloudStorageAccountModel struct {
	value *WasabiCloudStorageAccountModel
	isSet bool
}

func (v NullableWasabiCloudStorageAccountModel) Get() *WasabiCloudStorageAccountModel {
	return v.value
}

func (v *NullableWasabiCloudStorageAccountModel) Set(val *WasabiCloudStorageAccountModel) {
	v.value = val
	v.isSet = true
}

func (v NullableWasabiCloudStorageAccountModel) IsSet() bool {
	return v.isSet
}

func (v *NullableWasabiCloudStorageAccountModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWasabiCloudStorageAccountModel(val *WasabiCloudStorageAccountModel) *NullableWasabiCloudStorageAccountModel {
	return &NullableWasabiCloudStorageAccountModel{value: val, isSet: true}
}

func (v NullableWasabiCloudStorageAccountModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWasabiCloudStorageAccountModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


