/*
 * Veeam Backup & Replication REST API
 *
 * This document lists paths (endpoints) of the Veeam Backup & Replication REST API and operations that you can perform by sending HTTP requests to the paths.<br>Requests can contain parameters in their path, query and header. POST and PUT requests can include a request body with resource payload. In response, you receive a conventional HTTP response code, HTTP response header and an optional response body schema that contains a result model.<br>Parameters, request bodies, and response bodies are defined inline or refer to schemas defined globally. Some schemas are polymorphic.
 *
 * API version: 1.1-rev0
 * Contact: support@veeam.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// ViVMQuickMigrationSpec struct for ViVMQuickMigrationSpec
type ViVMQuickMigrationSpec struct {
	DestinationHost VmwareObjectModel `json:"destinationHost"`
	ResourcePool *VmwareObjectModel `json:"resourcePool,omitempty"`
	Folder *VmwareObjectModel `json:"folder,omitempty"`
	Datastore *VmwareObjectModel `json:"datastore,omitempty"`
	SourceProxyIds *[]string `json:"sourceProxyIds,omitempty"`
	TargetProxyIds *[]string `json:"targetProxyIds,omitempty"`
	VeeamQMEnabled *bool `json:"VeeamQMEnabled,omitempty"`
	DeleteSourceVmsFiles *bool `json:"DeleteSourceVmsFiles,omitempty"`
}

// NewViVMQuickMigrationSpec instantiates a new ViVMQuickMigrationSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewViVMQuickMigrationSpec(destinationHost VmwareObjectModel, ) *ViVMQuickMigrationSpec {
	this := ViVMQuickMigrationSpec{}
	this.DestinationHost = destinationHost
	return &this
}

// NewViVMQuickMigrationSpecWithDefaults instantiates a new ViVMQuickMigrationSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewViVMQuickMigrationSpecWithDefaults() *ViVMQuickMigrationSpec {
	this := ViVMQuickMigrationSpec{}
	return &this
}

// GetDestinationHost returns the DestinationHost field value
func (o *ViVMQuickMigrationSpec) GetDestinationHost() VmwareObjectModel {
	if o == nil  {
		var ret VmwareObjectModel
		return ret
	}

	return o.DestinationHost
}

// GetDestinationHostOk returns a tuple with the DestinationHost field value
// and a boolean to check if the value has been set.
func (o *ViVMQuickMigrationSpec) GetDestinationHostOk() (*VmwareObjectModel, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.DestinationHost, true
}

// SetDestinationHost sets field value
func (o *ViVMQuickMigrationSpec) SetDestinationHost(v VmwareObjectModel) {
	o.DestinationHost = v
}

// GetResourcePool returns the ResourcePool field value if set, zero value otherwise.
func (o *ViVMQuickMigrationSpec) GetResourcePool() VmwareObjectModel {
	if o == nil || o.ResourcePool == nil {
		var ret VmwareObjectModel
		return ret
	}
	return *o.ResourcePool
}

// GetResourcePoolOk returns a tuple with the ResourcePool field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViVMQuickMigrationSpec) GetResourcePoolOk() (*VmwareObjectModel, bool) {
	if o == nil || o.ResourcePool == nil {
		return nil, false
	}
	return o.ResourcePool, true
}

// HasResourcePool returns a boolean if a field has been set.
func (o *ViVMQuickMigrationSpec) HasResourcePool() bool {
	if o != nil && o.ResourcePool != nil {
		return true
	}

	return false
}

// SetResourcePool gets a reference to the given VmwareObjectModel and assigns it to the ResourcePool field.
func (o *ViVMQuickMigrationSpec) SetResourcePool(v VmwareObjectModel) {
	o.ResourcePool = &v
}

// GetFolder returns the Folder field value if set, zero value otherwise.
func (o *ViVMQuickMigrationSpec) GetFolder() VmwareObjectModel {
	if o == nil || o.Folder == nil {
		var ret VmwareObjectModel
		return ret
	}
	return *o.Folder
}

// GetFolderOk returns a tuple with the Folder field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViVMQuickMigrationSpec) GetFolderOk() (*VmwareObjectModel, bool) {
	if o == nil || o.Folder == nil {
		return nil, false
	}
	return o.Folder, true
}

// HasFolder returns a boolean if a field has been set.
func (o *ViVMQuickMigrationSpec) HasFolder() bool {
	if o != nil && o.Folder != nil {
		return true
	}

	return false
}

// SetFolder gets a reference to the given VmwareObjectModel and assigns it to the Folder field.
func (o *ViVMQuickMigrationSpec) SetFolder(v VmwareObjectModel) {
	o.Folder = &v
}

// GetDatastore returns the Datastore field value if set, zero value otherwise.
func (o *ViVMQuickMigrationSpec) GetDatastore() VmwareObjectModel {
	if o == nil || o.Datastore == nil {
		var ret VmwareObjectModel
		return ret
	}
	return *o.Datastore
}

// GetDatastoreOk returns a tuple with the Datastore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViVMQuickMigrationSpec) GetDatastoreOk() (*VmwareObjectModel, bool) {
	if o == nil || o.Datastore == nil {
		return nil, false
	}
	return o.Datastore, true
}

// HasDatastore returns a boolean if a field has been set.
func (o *ViVMQuickMigrationSpec) HasDatastore() bool {
	if o != nil && o.Datastore != nil {
		return true
	}

	return false
}

// SetDatastore gets a reference to the given VmwareObjectModel and assigns it to the Datastore field.
func (o *ViVMQuickMigrationSpec) SetDatastore(v VmwareObjectModel) {
	o.Datastore = &v
}

// GetSourceProxyIds returns the SourceProxyIds field value if set, zero value otherwise.
func (o *ViVMQuickMigrationSpec) GetSourceProxyIds() []string {
	if o == nil || o.SourceProxyIds == nil {
		var ret []string
		return ret
	}
	return *o.SourceProxyIds
}

// GetSourceProxyIdsOk returns a tuple with the SourceProxyIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViVMQuickMigrationSpec) GetSourceProxyIdsOk() (*[]string, bool) {
	if o == nil || o.SourceProxyIds == nil {
		return nil, false
	}
	return o.SourceProxyIds, true
}

// HasSourceProxyIds returns a boolean if a field has been set.
func (o *ViVMQuickMigrationSpec) HasSourceProxyIds() bool {
	if o != nil && o.SourceProxyIds != nil {
		return true
	}

	return false
}

// SetSourceProxyIds gets a reference to the given []string and assigns it to the SourceProxyIds field.
func (o *ViVMQuickMigrationSpec) SetSourceProxyIds(v []string) {
	o.SourceProxyIds = &v
}

// GetTargetProxyIds returns the TargetProxyIds field value if set, zero value otherwise.
func (o *ViVMQuickMigrationSpec) GetTargetProxyIds() []string {
	if o == nil || o.TargetProxyIds == nil {
		var ret []string
		return ret
	}
	return *o.TargetProxyIds
}

// GetTargetProxyIdsOk returns a tuple with the TargetProxyIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViVMQuickMigrationSpec) GetTargetProxyIdsOk() (*[]string, bool) {
	if o == nil || o.TargetProxyIds == nil {
		return nil, false
	}
	return o.TargetProxyIds, true
}

// HasTargetProxyIds returns a boolean if a field has been set.
func (o *ViVMQuickMigrationSpec) HasTargetProxyIds() bool {
	if o != nil && o.TargetProxyIds != nil {
		return true
	}

	return false
}

// SetTargetProxyIds gets a reference to the given []string and assigns it to the TargetProxyIds field.
func (o *ViVMQuickMigrationSpec) SetTargetProxyIds(v []string) {
	o.TargetProxyIds = &v
}

// GetVeeamQMEnabled returns the VeeamQMEnabled field value if set, zero value otherwise.
func (o *ViVMQuickMigrationSpec) GetVeeamQMEnabled() bool {
	if o == nil || o.VeeamQMEnabled == nil {
		var ret bool
		return ret
	}
	return *o.VeeamQMEnabled
}

// GetVeeamQMEnabledOk returns a tuple with the VeeamQMEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViVMQuickMigrationSpec) GetVeeamQMEnabledOk() (*bool, bool) {
	if o == nil || o.VeeamQMEnabled == nil {
		return nil, false
	}
	return o.VeeamQMEnabled, true
}

// HasVeeamQMEnabled returns a boolean if a field has been set.
func (o *ViVMQuickMigrationSpec) HasVeeamQMEnabled() bool {
	if o != nil && o.VeeamQMEnabled != nil {
		return true
	}

	return false
}

// SetVeeamQMEnabled gets a reference to the given bool and assigns it to the VeeamQMEnabled field.
func (o *ViVMQuickMigrationSpec) SetVeeamQMEnabled(v bool) {
	o.VeeamQMEnabled = &v
}

// GetDeleteSourceVmsFiles returns the DeleteSourceVmsFiles field value if set, zero value otherwise.
func (o *ViVMQuickMigrationSpec) GetDeleteSourceVmsFiles() bool {
	if o == nil || o.DeleteSourceVmsFiles == nil {
		var ret bool
		return ret
	}
	return *o.DeleteSourceVmsFiles
}

// GetDeleteSourceVmsFilesOk returns a tuple with the DeleteSourceVmsFiles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViVMQuickMigrationSpec) GetDeleteSourceVmsFilesOk() (*bool, bool) {
	if o == nil || o.DeleteSourceVmsFiles == nil {
		return nil, false
	}
	return o.DeleteSourceVmsFiles, true
}

// HasDeleteSourceVmsFiles returns a boolean if a field has been set.
func (o *ViVMQuickMigrationSpec) HasDeleteSourceVmsFiles() bool {
	if o != nil && o.DeleteSourceVmsFiles != nil {
		return true
	}

	return false
}

// SetDeleteSourceVmsFiles gets a reference to the given bool and assigns it to the DeleteSourceVmsFiles field.
func (o *ViVMQuickMigrationSpec) SetDeleteSourceVmsFiles(v bool) {
	o.DeleteSourceVmsFiles = &v
}

func (o ViVMQuickMigrationSpec) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["destinationHost"] = o.DestinationHost
	}
	if o.ResourcePool != nil {
		toSerialize["resourcePool"] = o.ResourcePool
	}
	if o.Folder != nil {
		toSerialize["folder"] = o.Folder
	}
	if o.Datastore != nil {
		toSerialize["datastore"] = o.Datastore
	}
	if o.SourceProxyIds != nil {
		toSerialize["sourceProxyIds"] = o.SourceProxyIds
	}
	if o.TargetProxyIds != nil {
		toSerialize["targetProxyIds"] = o.TargetProxyIds
	}
	if o.VeeamQMEnabled != nil {
		toSerialize["VeeamQMEnabled"] = o.VeeamQMEnabled
	}
	if o.DeleteSourceVmsFiles != nil {
		toSerialize["DeleteSourceVmsFiles"] = o.DeleteSourceVmsFiles
	}
	return json.Marshal(toSerialize)
}

type NullableViVMQuickMigrationSpec struct {
	value *ViVMQuickMigrationSpec
	isSet bool
}

func (v NullableViVMQuickMigrationSpec) Get() *ViVMQuickMigrationSpec {
	return v.value
}

func (v *NullableViVMQuickMigrationSpec) Set(val *ViVMQuickMigrationSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableViVMQuickMigrationSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableViVMQuickMigrationSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableViVMQuickMigrationSpec(val *ViVMQuickMigrationSpec) *NullableViVMQuickMigrationSpec {
	return &NullableViVMQuickMigrationSpec{value: val, isSet: true}
}

func (v NullableViVMQuickMigrationSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableViVMQuickMigrationSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


