/*
 * Veeam Backup & Replication REST API
 *
 * This document lists paths (endpoints) of the Veeam Backup & Replication REST API and operations that you can perform by sending HTTP requests to the paths.<br>Requests can contain parameters in their path, query and header. POST and PUT requests can include a request body with resource payload. In response, you receive a conventional HTTP response code, HTTP response header and an optional response body schema that contains a result model.<br>Parameters, request bodies, and response bodies are defined inline or refer to schemas defined globally. Some schemas are polymorphic.
 *
 * API version: 1.1-rev0
 * Contact: support@veeam.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// IBMCloudStorageAccountImportModel struct for IBMCloudStorageAccountImportModel
type IBMCloudStorageAccountImportModel struct {
	ServicePoint string `json:"servicePoint"`
	RegionId string `json:"regionId"`
	Credentials CredentialsImportModel `json:"credentials"`
	GatewayServer RepositoryShareGatewayImportSpec `json:"gatewayServer"`
}

// NewIBMCloudStorageAccountImportModel instantiates a new IBMCloudStorageAccountImportModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIBMCloudStorageAccountImportModel(servicePoint string, regionId string, credentials CredentialsImportModel, gatewayServer RepositoryShareGatewayImportSpec, ) *IBMCloudStorageAccountImportModel {
	this := IBMCloudStorageAccountImportModel{}
	this.ServicePoint = servicePoint
	this.RegionId = regionId
	this.Credentials = credentials
	this.GatewayServer = gatewayServer
	return &this
}

// NewIBMCloudStorageAccountImportModelWithDefaults instantiates a new IBMCloudStorageAccountImportModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIBMCloudStorageAccountImportModelWithDefaults() *IBMCloudStorageAccountImportModel {
	this := IBMCloudStorageAccountImportModel{}
	return &this
}

// GetServicePoint returns the ServicePoint field value
func (o *IBMCloudStorageAccountImportModel) GetServicePoint() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.ServicePoint
}

// GetServicePointOk returns a tuple with the ServicePoint field value
// and a boolean to check if the value has been set.
func (o *IBMCloudStorageAccountImportModel) GetServicePointOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ServicePoint, true
}

// SetServicePoint sets field value
func (o *IBMCloudStorageAccountImportModel) SetServicePoint(v string) {
	o.ServicePoint = v
}

// GetRegionId returns the RegionId field value
func (o *IBMCloudStorageAccountImportModel) GetRegionId() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.RegionId
}

// GetRegionIdOk returns a tuple with the RegionId field value
// and a boolean to check if the value has been set.
func (o *IBMCloudStorageAccountImportModel) GetRegionIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.RegionId, true
}

// SetRegionId sets field value
func (o *IBMCloudStorageAccountImportModel) SetRegionId(v string) {
	o.RegionId = v
}

// GetCredentials returns the Credentials field value
func (o *IBMCloudStorageAccountImportModel) GetCredentials() CredentialsImportModel {
	if o == nil  {
		var ret CredentialsImportModel
		return ret
	}

	return o.Credentials
}

// GetCredentialsOk returns a tuple with the Credentials field value
// and a boolean to check if the value has been set.
func (o *IBMCloudStorageAccountImportModel) GetCredentialsOk() (*CredentialsImportModel, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Credentials, true
}

// SetCredentials sets field value
func (o *IBMCloudStorageAccountImportModel) SetCredentials(v CredentialsImportModel) {
	o.Credentials = v
}

// GetGatewayServer returns the GatewayServer field value
func (o *IBMCloudStorageAccountImportModel) GetGatewayServer() RepositoryShareGatewayImportSpec {
	if o == nil  {
		var ret RepositoryShareGatewayImportSpec
		return ret
	}

	return o.GatewayServer
}

// GetGatewayServerOk returns a tuple with the GatewayServer field value
// and a boolean to check if the value has been set.
func (o *IBMCloudStorageAccountImportModel) GetGatewayServerOk() (*RepositoryShareGatewayImportSpec, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.GatewayServer, true
}

// SetGatewayServer sets field value
func (o *IBMCloudStorageAccountImportModel) SetGatewayServer(v RepositoryShareGatewayImportSpec) {
	o.GatewayServer = v
}

func (o IBMCloudStorageAccountImportModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["servicePoint"] = o.ServicePoint
	}
	if true {
		toSerialize["regionId"] = o.RegionId
	}
	if true {
		toSerialize["credentials"] = o.Credentials
	}
	if true {
		toSerialize["gatewayServer"] = o.GatewayServer
	}
	return json.Marshal(toSerialize)
}

type NullableIBMCloudStorageAccountImportModel struct {
	value *IBMCloudStorageAccountImportModel
	isSet bool
}

func (v NullableIBMCloudStorageAccountImportModel) Get() *IBMCloudStorageAccountImportModel {
	return v.value
}

func (v *NullableIBMCloudStorageAccountImportModel) Set(val *IBMCloudStorageAccountImportModel) {
	v.value = val
	v.isSet = true
}

func (v NullableIBMCloudStorageAccountImportModel) IsSet() bool {
	return v.isSet
}

func (v *NullableIBMCloudStorageAccountImportModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIBMCloudStorageAccountImportModel(val *IBMCloudStorageAccountImportModel) *NullableIBMCloudStorageAccountImportModel {
	return &NullableIBMCloudStorageAccountImportModel{value: val, isSet: true}
}

func (v NullableIBMCloudStorageAccountImportModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIBMCloudStorageAccountImportModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


