/*
 * Veeam Backup & Replication REST API
 *
 * This document lists paths (endpoints) of the Veeam Backup & Replication REST API and operations that you can perform by sending HTTP requests to the paths.<br>Requests can contain parameters in their path, query and header. POST and PUT requests can include a request body with resource payload. In response, you receive a conventional HTTP response code, HTTP response header and an optional response body schema that contains a result model.<br>Parameters, request bodies, and response bodies are defined inline or refer to schemas defined globally. Some schemas are polymorphic.
 *
 * API version: 1.1-rev0
 * Contact: support@veeam.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// CloudCredentialsPasswordSpec struct for CloudCredentialsPasswordSpec
type CloudCredentialsPasswordSpec struct {
	// New secret key.
	NewSecretKey *string `json:"newSecretKey,omitempty"`
}

// NewCloudCredentialsPasswordSpec instantiates a new CloudCredentialsPasswordSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCloudCredentialsPasswordSpec() *CloudCredentialsPasswordSpec {
	this := CloudCredentialsPasswordSpec{}
	return &this
}

// NewCloudCredentialsPasswordSpecWithDefaults instantiates a new CloudCredentialsPasswordSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCloudCredentialsPasswordSpecWithDefaults() *CloudCredentialsPasswordSpec {
	this := CloudCredentialsPasswordSpec{}
	return &this
}

// GetNewSecretKey returns the NewSecretKey field value if set, zero value otherwise.
func (o *CloudCredentialsPasswordSpec) GetNewSecretKey() string {
	if o == nil || o.NewSecretKey == nil {
		var ret string
		return ret
	}
	return *o.NewSecretKey
}

// GetNewSecretKeyOk returns a tuple with the NewSecretKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudCredentialsPasswordSpec) GetNewSecretKeyOk() (*string, bool) {
	if o == nil || o.NewSecretKey == nil {
		return nil, false
	}
	return o.NewSecretKey, true
}

// HasNewSecretKey returns a boolean if a field has been set.
func (o *CloudCredentialsPasswordSpec) HasNewSecretKey() bool {
	if o != nil && o.NewSecretKey != nil {
		return true
	}

	return false
}

// SetNewSecretKey gets a reference to the given string and assigns it to the NewSecretKey field.
func (o *CloudCredentialsPasswordSpec) SetNewSecretKey(v string) {
	o.NewSecretKey = &v
}

func (o CloudCredentialsPasswordSpec) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.NewSecretKey != nil {
		toSerialize["newSecretKey"] = o.NewSecretKey
	}
	return json.Marshal(toSerialize)
}

type NullableCloudCredentialsPasswordSpec struct {
	value *CloudCredentialsPasswordSpec
	isSet bool
}

func (v NullableCloudCredentialsPasswordSpec) Get() *CloudCredentialsPasswordSpec {
	return v.value
}

func (v *NullableCloudCredentialsPasswordSpec) Set(val *CloudCredentialsPasswordSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableCloudCredentialsPasswordSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableCloudCredentialsPasswordSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCloudCredentialsPasswordSpec(val *CloudCredentialsPasswordSpec) *NullableCloudCredentialsPasswordSpec {
	return &NullableCloudCredentialsPasswordSpec{value: val, isSet: true}
}

func (v NullableCloudCredentialsPasswordSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCloudCredentialsPasswordSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


