/*
 * Veeam Backup & Replication REST API
 *
 * This document lists paths (endpoints) of the Veeam Backup & Replication REST API and operations that you can perform by sending HTTP requests to the paths.<br>Requests can contain parameters in their path, query and header. POST and PUT requests can include a request body with resource payload. In response, you receive a conventional HTTP response code, HTTP response header and an optional response body schema that contains a result model.<br>Parameters, request bodies, and response bodies are defined inline or refer to schemas defined globally. Some schemas are polymorphic.
 *
 * API version: 1.1-rev0
 * Contact: support@veeam.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// AmazonS3StorageModelAllOf struct for AmazonS3StorageModelAllOf
type AmazonS3StorageModelAllOf struct {
	EnableTaskLimit *bool `json:"enableTaskLimit,omitempty"`
	// Maximum number of concurrent tasks.
	MaxTaskCount *int32 `json:"maxTaskCount,omitempty"`
	Account AmazonS3StorageAccountModel `json:"account"`
	Bucket AmazonS3StorageBucketModel `json:"bucket"`
	MountServer MountServerSettingsModel `json:"mountServer"`
	ProxyAppliance *AmazonS3StorageProxyApplianceModel `json:"proxyAppliance,omitempty"`
}

// NewAmazonS3StorageModelAllOf instantiates a new AmazonS3StorageModelAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAmazonS3StorageModelAllOf(account AmazonS3StorageAccountModel, bucket AmazonS3StorageBucketModel, mountServer MountServerSettingsModel, ) *AmazonS3StorageModelAllOf {
	this := AmazonS3StorageModelAllOf{}
	this.Account = account
	this.Bucket = bucket
	this.MountServer = mountServer
	return &this
}

// NewAmazonS3StorageModelAllOfWithDefaults instantiates a new AmazonS3StorageModelAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAmazonS3StorageModelAllOfWithDefaults() *AmazonS3StorageModelAllOf {
	this := AmazonS3StorageModelAllOf{}
	return &this
}

// GetEnableTaskLimit returns the EnableTaskLimit field value if set, zero value otherwise.
func (o *AmazonS3StorageModelAllOf) GetEnableTaskLimit() bool {
	if o == nil || o.EnableTaskLimit == nil {
		var ret bool
		return ret
	}
	return *o.EnableTaskLimit
}

// GetEnableTaskLimitOk returns a tuple with the EnableTaskLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AmazonS3StorageModelAllOf) GetEnableTaskLimitOk() (*bool, bool) {
	if o == nil || o.EnableTaskLimit == nil {
		return nil, false
	}
	return o.EnableTaskLimit, true
}

// HasEnableTaskLimit returns a boolean if a field has been set.
func (o *AmazonS3StorageModelAllOf) HasEnableTaskLimit() bool {
	if o != nil && o.EnableTaskLimit != nil {
		return true
	}

	return false
}

// SetEnableTaskLimit gets a reference to the given bool and assigns it to the EnableTaskLimit field.
func (o *AmazonS3StorageModelAllOf) SetEnableTaskLimit(v bool) {
	o.EnableTaskLimit = &v
}

// GetMaxTaskCount returns the MaxTaskCount field value if set, zero value otherwise.
func (o *AmazonS3StorageModelAllOf) GetMaxTaskCount() int32 {
	if o == nil || o.MaxTaskCount == nil {
		var ret int32
		return ret
	}
	return *o.MaxTaskCount
}

// GetMaxTaskCountOk returns a tuple with the MaxTaskCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AmazonS3StorageModelAllOf) GetMaxTaskCountOk() (*int32, bool) {
	if o == nil || o.MaxTaskCount == nil {
		return nil, false
	}
	return o.MaxTaskCount, true
}

// HasMaxTaskCount returns a boolean if a field has been set.
func (o *AmazonS3StorageModelAllOf) HasMaxTaskCount() bool {
	if o != nil && o.MaxTaskCount != nil {
		return true
	}

	return false
}

// SetMaxTaskCount gets a reference to the given int32 and assigns it to the MaxTaskCount field.
func (o *AmazonS3StorageModelAllOf) SetMaxTaskCount(v int32) {
	o.MaxTaskCount = &v
}

// GetAccount returns the Account field value
func (o *AmazonS3StorageModelAllOf) GetAccount() AmazonS3StorageAccountModel {
	if o == nil  {
		var ret AmazonS3StorageAccountModel
		return ret
	}

	return o.Account
}

// GetAccountOk returns a tuple with the Account field value
// and a boolean to check if the value has been set.
func (o *AmazonS3StorageModelAllOf) GetAccountOk() (*AmazonS3StorageAccountModel, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Account, true
}

// SetAccount sets field value
func (o *AmazonS3StorageModelAllOf) SetAccount(v AmazonS3StorageAccountModel) {
	o.Account = v
}

// GetBucket returns the Bucket field value
func (o *AmazonS3StorageModelAllOf) GetBucket() AmazonS3StorageBucketModel {
	if o == nil  {
		var ret AmazonS3StorageBucketModel
		return ret
	}

	return o.Bucket
}

// GetBucketOk returns a tuple with the Bucket field value
// and a boolean to check if the value has been set.
func (o *AmazonS3StorageModelAllOf) GetBucketOk() (*AmazonS3StorageBucketModel, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Bucket, true
}

// SetBucket sets field value
func (o *AmazonS3StorageModelAllOf) SetBucket(v AmazonS3StorageBucketModel) {
	o.Bucket = v
}

// GetMountServer returns the MountServer field value
func (o *AmazonS3StorageModelAllOf) GetMountServer() MountServerSettingsModel {
	if o == nil  {
		var ret MountServerSettingsModel
		return ret
	}

	return o.MountServer
}

// GetMountServerOk returns a tuple with the MountServer field value
// and a boolean to check if the value has been set.
func (o *AmazonS3StorageModelAllOf) GetMountServerOk() (*MountServerSettingsModel, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.MountServer, true
}

// SetMountServer sets field value
func (o *AmazonS3StorageModelAllOf) SetMountServer(v MountServerSettingsModel) {
	o.MountServer = v
}

// GetProxyAppliance returns the ProxyAppliance field value if set, zero value otherwise.
func (o *AmazonS3StorageModelAllOf) GetProxyAppliance() AmazonS3StorageProxyApplianceModel {
	if o == nil || o.ProxyAppliance == nil {
		var ret AmazonS3StorageProxyApplianceModel
		return ret
	}
	return *o.ProxyAppliance
}

// GetProxyApplianceOk returns a tuple with the ProxyAppliance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AmazonS3StorageModelAllOf) GetProxyApplianceOk() (*AmazonS3StorageProxyApplianceModel, bool) {
	if o == nil || o.ProxyAppliance == nil {
		return nil, false
	}
	return o.ProxyAppliance, true
}

// HasProxyAppliance returns a boolean if a field has been set.
func (o *AmazonS3StorageModelAllOf) HasProxyAppliance() bool {
	if o != nil && o.ProxyAppliance != nil {
		return true
	}

	return false
}

// SetProxyAppliance gets a reference to the given AmazonS3StorageProxyApplianceModel and assigns it to the ProxyAppliance field.
func (o *AmazonS3StorageModelAllOf) SetProxyAppliance(v AmazonS3StorageProxyApplianceModel) {
	o.ProxyAppliance = &v
}

func (o AmazonS3StorageModelAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.EnableTaskLimit != nil {
		toSerialize["enableTaskLimit"] = o.EnableTaskLimit
	}
	if o.MaxTaskCount != nil {
		toSerialize["maxTaskCount"] = o.MaxTaskCount
	}
	if true {
		toSerialize["account"] = o.Account
	}
	if true {
		toSerialize["bucket"] = o.Bucket
	}
	if true {
		toSerialize["mountServer"] = o.MountServer
	}
	if o.ProxyAppliance != nil {
		toSerialize["proxyAppliance"] = o.ProxyAppliance
	}
	return json.Marshal(toSerialize)
}

type NullableAmazonS3StorageModelAllOf struct {
	value *AmazonS3StorageModelAllOf
	isSet bool
}

func (v NullableAmazonS3StorageModelAllOf) Get() *AmazonS3StorageModelAllOf {
	return v.value
}

func (v *NullableAmazonS3StorageModelAllOf) Set(val *AmazonS3StorageModelAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableAmazonS3StorageModelAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableAmazonS3StorageModelAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAmazonS3StorageModelAllOf(val *AmazonS3StorageModelAllOf) *NullableAmazonS3StorageModelAllOf {
	return &NullableAmazonS3StorageModelAllOf{value: val, isSet: true}
}

func (v NullableAmazonS3StorageModelAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAmazonS3StorageModelAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


