/*
 * Veeam Backup & Replication REST API
 *
 * This document lists paths (endpoints) of the Veeam Backup & Replication REST API and operations that you can perform by sending HTTP requests to the paths.<br>Requests can contain parameters in their path, query and header. POST and PUT requests can include a request body with resource payload. In response, you receive a conventional HTTP response code, HTTP response header and an optional response body schema that contains a result model.<br>Parameters, request bodies, and response bodies are defined inline or refer to schemas defined globally. Some schemas are polymorphic.
 *
 * API version: 1.1-rev0
 * Contact: support@veeam.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)

// EInstantViVmRecoveryBiosUuidPolicyType BIOS UUID policy for the restored VM.
type EInstantViVmRecoveryBiosUuidPolicyType string

// List of EInstantViVmRecoveryBiosUuidPolicyType
const (
	EINSTANTVIVMRECOVERYBIOSUUIDPOLICYTYPE_PRESERVE EInstantViVmRecoveryBiosUuidPolicyType = "preserve"
	EINSTANTVIVMRECOVERYBIOSUUIDPOLICYTYPE_GENERATE_NEW EInstantViVmRecoveryBiosUuidPolicyType = "generateNew"
)

func (v *EInstantViVmRecoveryBiosUuidPolicyType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := EInstantViVmRecoveryBiosUuidPolicyType(value)
	for _, existing := range []EInstantViVmRecoveryBiosUuidPolicyType{ "preserve", "generateNew",   } {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid EInstantViVmRecoveryBiosUuidPolicyType", value)
}

// Ptr returns reference to EInstantViVmRecoveryBiosUuidPolicyType value
func (v EInstantViVmRecoveryBiosUuidPolicyType) Ptr() *EInstantViVmRecoveryBiosUuidPolicyType {
	return &v
}

type NullableEInstantViVmRecoveryBiosUuidPolicyType struct {
	value *EInstantViVmRecoveryBiosUuidPolicyType
	isSet bool
}

func (v NullableEInstantViVmRecoveryBiosUuidPolicyType) Get() *EInstantViVmRecoveryBiosUuidPolicyType {
	return v.value
}

func (v *NullableEInstantViVmRecoveryBiosUuidPolicyType) Set(val *EInstantViVmRecoveryBiosUuidPolicyType) {
	v.value = val
	v.isSet = true
}

func (v NullableEInstantViVmRecoveryBiosUuidPolicyType) IsSet() bool {
	return v.isSet
}

func (v *NullableEInstantViVmRecoveryBiosUuidPolicyType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEInstantViVmRecoveryBiosUuidPolicyType(val *EInstantViVmRecoveryBiosUuidPolicyType) *NullableEInstantViVmRecoveryBiosUuidPolicyType {
	return &NullableEInstantViVmRecoveryBiosUuidPolicyType{value: val, isSet: true}
}

func (v NullableEInstantViVmRecoveryBiosUuidPolicyType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEInstantViVmRecoveryBiosUuidPolicyType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

