/*
 * Veeam Backup & Replication REST API
 *
 * This document lists paths (endpoints) of the Veeam Backup & Replication REST API and operations that you can perform by sending HTTP requests to the paths.<br>Requests can contain parameters in their path, query and header. POST and PUT requests can include a request body with resource payload. In response, you receive a conventional HTTP response code, HTTP response header and an optional response body schema that contains a result model.<br>Parameters, request bodies, and response bodies are defined inline or refer to schemas defined globally. Some schemas are polymorphic.
 *
 * API version: 1.1-rev0
 * Contact: support@veeam.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)

// EConsumptionLimitKind Measurement unit.
type EConsumptionLimitKind string

// List of EConsumptionLimitKind
const (
	ECONSUMPTIONLIMITKIND_TB EConsumptionLimitKind = "TB"
	ECONSUMPTIONLIMITKIND_PB EConsumptionLimitKind = "PB"
)

func (v *EConsumptionLimitKind) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := EConsumptionLimitKind(value)
	for _, existing := range []EConsumptionLimitKind{ "TB", "PB",   } {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid EConsumptionLimitKind", value)
}

// Ptr returns reference to EConsumptionLimitKind value
func (v EConsumptionLimitKind) Ptr() *EConsumptionLimitKind {
	return &v
}

type NullableEConsumptionLimitKind struct {
	value *EConsumptionLimitKind
	isSet bool
}

func (v NullableEConsumptionLimitKind) Get() *EConsumptionLimitKind {
	return v.value
}

func (v *NullableEConsumptionLimitKind) Set(val *EConsumptionLimitKind) {
	v.value = val
	v.isSet = true
}

func (v NullableEConsumptionLimitKind) IsSet() bool {
	return v.isSet
}

func (v *NullableEConsumptionLimitKind) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEConsumptionLimitKind(val *EConsumptionLimitKind) *NullableEConsumptionLimitKind {
	return &NullableEConsumptionLimitKind{value: val, isSet: true}
}

func (v NullableEConsumptionLimitKind) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEConsumptionLimitKind) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

