/*
 * Veeam Backup & Replication REST API
 *
 * This document lists paths (endpoints) of the Veeam Backup & Replication REST API and operations that you can perform by sending HTTP requests to the paths.<br>Requests can contain parameters in their path, query and header. POST and PUT requests can include a request body with resource payload. In response, you receive a conventional HTTP response code, HTTP response header and an optional response body schema that contains a result model.<br>Parameters, request bodies, and response bodies are defined inline or refer to schemas defined globally. Some schemas are polymorphic.
 *
 * API version: 1.1-rev0
 * Contact: support@veeam.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)

// EDiskCreationMode Format of restored VM disks.
type EDiskCreationMode string

// List of EDiskCreationMode
const (
	EDISKCREATIONMODE_SOURCE EDiskCreationMode = "Source"
	EDISKCREATIONMODE_THICK EDiskCreationMode = "Thick"
	EDISKCREATIONMODE_THIN EDiskCreationMode = "Thin"
	EDISKCREATIONMODE_THICK_EAGER_ZEROED EDiskCreationMode = "ThickEagerZeroed"
)

func (v *EDiskCreationMode) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := EDiskCreationMode(value)
	for _, existing := range []EDiskCreationMode{ "Source", "Thick", "Thin", "ThickEagerZeroed",   } {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid EDiskCreationMode", value)
}

// Ptr returns reference to EDiskCreationMode value
func (v EDiskCreationMode) Ptr() *EDiskCreationMode {
	return &v
}

type NullableEDiskCreationMode struct {
	value *EDiskCreationMode
	isSet bool
}

func (v NullableEDiskCreationMode) Get() *EDiskCreationMode {
	return v.value
}

func (v *NullableEDiskCreationMode) Set(val *EDiskCreationMode) {
	v.value = val
	v.isSet = true
}

func (v NullableEDiskCreationMode) IsSet() bool {
	return v.isSet
}

func (v *NullableEDiskCreationMode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEDiskCreationMode(val *EDiskCreationMode) *NullableEDiskCreationMode {
	return &NullableEDiskCreationMode{value: val, isSet: true}
}

func (v NullableEDiskCreationMode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEDiskCreationMode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

