/*
 * Veeam Backup & Replication REST API
 *
 * This document lists paths (endpoints) of the Veeam Backup & Replication REST API and operations that you can perform by sending HTTP requests to the paths.<br>Requests can contain parameters in their path, query and header. POST and PUT requests can include a request body with resource payload. In response, you receive a conventional HTTP response code, HTTP response header and an optional response body schema that contains a result model.<br>Parameters, request bodies, and response bodies are defined inline or refer to schemas defined globally. Some schemas are polymorphic.
 *
 * API version: 1.1-rev0
 * Contact: support@veeam.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// WasabiCloudStorageBucketBrowserModel struct for WasabiCloudStorageBucketBrowserModel
type WasabiCloudStorageBucketBrowserModel struct {
	Name *string `json:"name,omitempty"`
	Folders *[]string `json:"folders,omitempty"`
}

// NewWasabiCloudStorageBucketBrowserModel instantiates a new WasabiCloudStorageBucketBrowserModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWasabiCloudStorageBucketBrowserModel() *WasabiCloudStorageBucketBrowserModel {
	this := WasabiCloudStorageBucketBrowserModel{}
	return &this
}

// NewWasabiCloudStorageBucketBrowserModelWithDefaults instantiates a new WasabiCloudStorageBucketBrowserModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWasabiCloudStorageBucketBrowserModelWithDefaults() *WasabiCloudStorageBucketBrowserModel {
	this := WasabiCloudStorageBucketBrowserModel{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *WasabiCloudStorageBucketBrowserModel) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WasabiCloudStorageBucketBrowserModel) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *WasabiCloudStorageBucketBrowserModel) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *WasabiCloudStorageBucketBrowserModel) SetName(v string) {
	o.Name = &v
}

// GetFolders returns the Folders field value if set, zero value otherwise.
func (o *WasabiCloudStorageBucketBrowserModel) GetFolders() []string {
	if o == nil || o.Folders == nil {
		var ret []string
		return ret
	}
	return *o.Folders
}

// GetFoldersOk returns a tuple with the Folders field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WasabiCloudStorageBucketBrowserModel) GetFoldersOk() (*[]string, bool) {
	if o == nil || o.Folders == nil {
		return nil, false
	}
	return o.Folders, true
}

// HasFolders returns a boolean if a field has been set.
func (o *WasabiCloudStorageBucketBrowserModel) HasFolders() bool {
	if o != nil && o.Folders != nil {
		return true
	}

	return false
}

// SetFolders gets a reference to the given []string and assigns it to the Folders field.
func (o *WasabiCloudStorageBucketBrowserModel) SetFolders(v []string) {
	o.Folders = &v
}

func (o WasabiCloudStorageBucketBrowserModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Folders != nil {
		toSerialize["folders"] = o.Folders
	}
	return json.Marshal(toSerialize)
}

type NullableWasabiCloudStorageBucketBrowserModel struct {
	value *WasabiCloudStorageBucketBrowserModel
	isSet bool
}

func (v NullableWasabiCloudStorageBucketBrowserModel) Get() *WasabiCloudStorageBucketBrowserModel {
	return v.value
}

func (v *NullableWasabiCloudStorageBucketBrowserModel) Set(val *WasabiCloudStorageBucketBrowserModel) {
	v.value = val
	v.isSet = true
}

func (v NullableWasabiCloudStorageBucketBrowserModel) IsSet() bool {
	return v.isSet
}

func (v *NullableWasabiCloudStorageBucketBrowserModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWasabiCloudStorageBucketBrowserModel(val *WasabiCloudStorageBucketBrowserModel) *NullableWasabiCloudStorageBucketBrowserModel {
	return &NullableWasabiCloudStorageBucketBrowserModel{value: val, isSet: true}
}

func (v NullableWasabiCloudStorageBucketBrowserModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWasabiCloudStorageBucketBrowserModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


