/*
 * Veeam Backup & Replication REST API
 *
 * This document lists paths (endpoints) of the Veeam Backup & Replication REST API and operations that you can perform by sending HTTP requests to the paths.<br>Requests can contain parameters in their path, query and header. POST and PUT requests can include a request body with resource payload. In response, you receive a conventional HTTP response code, HTTP response header and an optional response body schema that contains a result model.<br>Parameters, request bodies, and response bodies are defined inline or refer to schemas defined globally. Some schemas are polymorphic.
 *
 * API version: 1.1-rev0
 * Contact: support@veeam.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// AmazonVPCBrowserModel struct for AmazonVPCBrowserModel
type AmazonVPCBrowserModel struct {
	VpcName *string `json:"vpcName,omitempty"`
	Subnets *[]string `json:"subnets,omitempty"`
	SecurityGroups *[]string `json:"securityGroups,omitempty"`
}

// NewAmazonVPCBrowserModel instantiates a new AmazonVPCBrowserModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAmazonVPCBrowserModel() *AmazonVPCBrowserModel {
	this := AmazonVPCBrowserModel{}
	return &this
}

// NewAmazonVPCBrowserModelWithDefaults instantiates a new AmazonVPCBrowserModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAmazonVPCBrowserModelWithDefaults() *AmazonVPCBrowserModel {
	this := AmazonVPCBrowserModel{}
	return &this
}

// GetVpcName returns the VpcName field value if set, zero value otherwise.
func (o *AmazonVPCBrowserModel) GetVpcName() string {
	if o == nil || o.VpcName == nil {
		var ret string
		return ret
	}
	return *o.VpcName
}

// GetVpcNameOk returns a tuple with the VpcName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AmazonVPCBrowserModel) GetVpcNameOk() (*string, bool) {
	if o == nil || o.VpcName == nil {
		return nil, false
	}
	return o.VpcName, true
}

// HasVpcName returns a boolean if a field has been set.
func (o *AmazonVPCBrowserModel) HasVpcName() bool {
	if o != nil && o.VpcName != nil {
		return true
	}

	return false
}

// SetVpcName gets a reference to the given string and assigns it to the VpcName field.
func (o *AmazonVPCBrowserModel) SetVpcName(v string) {
	o.VpcName = &v
}

// GetSubnets returns the Subnets field value if set, zero value otherwise.
func (o *AmazonVPCBrowserModel) GetSubnets() []string {
	if o == nil || o.Subnets == nil {
		var ret []string
		return ret
	}
	return *o.Subnets
}

// GetSubnetsOk returns a tuple with the Subnets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AmazonVPCBrowserModel) GetSubnetsOk() (*[]string, bool) {
	if o == nil || o.Subnets == nil {
		return nil, false
	}
	return o.Subnets, true
}

// HasSubnets returns a boolean if a field has been set.
func (o *AmazonVPCBrowserModel) HasSubnets() bool {
	if o != nil && o.Subnets != nil {
		return true
	}

	return false
}

// SetSubnets gets a reference to the given []string and assigns it to the Subnets field.
func (o *AmazonVPCBrowserModel) SetSubnets(v []string) {
	o.Subnets = &v
}

// GetSecurityGroups returns the SecurityGroups field value if set, zero value otherwise.
func (o *AmazonVPCBrowserModel) GetSecurityGroups() []string {
	if o == nil || o.SecurityGroups == nil {
		var ret []string
		return ret
	}
	return *o.SecurityGroups
}

// GetSecurityGroupsOk returns a tuple with the SecurityGroups field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AmazonVPCBrowserModel) GetSecurityGroupsOk() (*[]string, bool) {
	if o == nil || o.SecurityGroups == nil {
		return nil, false
	}
	return o.SecurityGroups, true
}

// HasSecurityGroups returns a boolean if a field has been set.
func (o *AmazonVPCBrowserModel) HasSecurityGroups() bool {
	if o != nil && o.SecurityGroups != nil {
		return true
	}

	return false
}

// SetSecurityGroups gets a reference to the given []string and assigns it to the SecurityGroups field.
func (o *AmazonVPCBrowserModel) SetSecurityGroups(v []string) {
	o.SecurityGroups = &v
}

func (o AmazonVPCBrowserModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.VpcName != nil {
		toSerialize["vpcName"] = o.VpcName
	}
	if o.Subnets != nil {
		toSerialize["subnets"] = o.Subnets
	}
	if o.SecurityGroups != nil {
		toSerialize["securityGroups"] = o.SecurityGroups
	}
	return json.Marshal(toSerialize)
}

type NullableAmazonVPCBrowserModel struct {
	value *AmazonVPCBrowserModel
	isSet bool
}

func (v NullableAmazonVPCBrowserModel) Get() *AmazonVPCBrowserModel {
	return v.value
}

func (v *NullableAmazonVPCBrowserModel) Set(val *AmazonVPCBrowserModel) {
	v.value = val
	v.isSet = true
}

func (v NullableAmazonVPCBrowserModel) IsSet() bool {
	return v.isSet
}

func (v *NullableAmazonVPCBrowserModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAmazonVPCBrowserModel(val *AmazonVPCBrowserModel) *NullableAmazonVPCBrowserModel {
	return &NullableAmazonVPCBrowserModel{value: val, isSet: true}
}

func (v NullableAmazonVPCBrowserModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAmazonVPCBrowserModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


